// Jaanify MVP — Middleware (Auth Plugin + Error Handler)
// Generated by jaan.to backend-scaffold | 2026-02-09
// Fastify v5 patterns: setErrorHandler, NOT Express-style middleware

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import fp from "fastify-plugin";
import {
  hasZodFastifySchemaValidationErrors,
  isResponseSerializationError,
} from "fastify-type-provider-zod";
import { Prisma } from "@prisma/client";

// ── Auth Plugin ────────────────────────────────────

interface JwtPayload {
  sub: string; // user UUID
  email: string | null;
  iat: number;
  exp: number;
}

declare module "fastify" {
  interface FastifyRequest {
    userId: string;
    jwtPayload: JwtPayload;
  }
}

async function authPlugin(fastify: FastifyInstance) {
  fastify.decorateRequest("userId", "");
  fastify.decorateRequest("jwtPayload", null);

  fastify.addHook("onRequest", async (request: FastifyRequest, reply: FastifyReply) => {
    // Skip auth for public routes
    const publicPaths = [
      "/v1/auth/google",
      "/v1/auth/refresh",
      "/v1/auth/register",
      "/v1/guest-sessions",
      "/v1/health",
    ];

    const isPublic = publicPaths.some(
      (path) =>
        request.url === path ||
        request.url.startsWith("/v1/guest-sessions/") ||
        request.url.startsWith("/docs")
    );

    if (isPublic) return;

    const authHeader = request.headers.authorization;
    if (!authHeader?.startsWith("Bearer ")) {
      return reply.status(401).send({
        type: "https://api.jaanify.com/errors/unauthorized",
        status: 401,
        title: "Unauthorized",
        detail: "Missing or invalid Authorization header. Expected: Bearer <token>",
      });
    }

    const token = authHeader.slice(7);

    try {
      // TODO: Replace with actual JWT verification (jsonwebtoken or @fastify/jwt)
      // For scaffold: decode and validate structure
      const payload = decodeJwt(token);
      if (!payload || !payload.sub) {
        throw new Error("Invalid token payload");
      }

      if (payload.exp && payload.exp * 1000 < Date.now()) {
        return reply.status(401).send({
          type: "https://api.jaanify.com/errors/token-expired",
          status: 401,
          title: "Token Expired",
          detail: "Access token has expired. Use /auth/refresh to obtain a new token.",
        });
      }

      request.userId = payload.sub;
      request.jwtPayload = payload;
    } catch {
      return reply.status(401).send({
        type: "https://api.jaanify.com/errors/invalid-token",
        status: 401,
        title: "Invalid Token",
        detail: "The provided access token is invalid or malformed.",
      });
    }
  });
}

function decodeJwt(token: string): JwtPayload | null {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return null;
    const payload = JSON.parse(Buffer.from(parts[1]!, "base64url").toString());
    return payload as JwtPayload;
  } catch {
    return null;
  }
}

export const authMiddleware = fp(authPlugin, {
  name: "auth",
  fastify: "5.x",
});

// ── Error Handler (RFC 9457) ───────────────────────

export async function errorHandlerPlugin(fastify: FastifyInstance) {
  fastify.setErrorHandler((error, request, reply) => {
    const requestId = request.id;

    // 1. Zod validation errors (from fastify-type-provider-zod v6)
    if (hasZodFastifySchemaValidationErrors(error)) {
      const zodErrors = error.validation.map((v) => ({
        detail: v.message,
        pointer: v.instancePath || `/${v.params?.issue?.path?.join("/") ?? "unknown"}`,
      }));

      return reply.status(400).header("Content-Type", "application/problem+json").send({
        type: "https://api.jaanify.com/errors/validation",
        status: 400,
        title: "Validation Error",
        detail: `${zodErrors.length} validation error(s) in request`,
        instance: request.url,
        errors: zodErrors,
      });
    }

    // 2. Response serialization errors (server-side bug)
    if (isResponseSerializationError(error)) {
      request.log.error({ err: error }, "Response serialization failed");
      return reply.status(500).header("Content-Type", "application/problem+json").send({
        type: "https://api.jaanify.com/errors/internal",
        status: 500,
        title: "Internal Server Error",
        detail: "Response serialization failed.",
        instance: request.url,
      });
    }

    // 3. Prisma known errors
    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      switch (error.code) {
        case "P2002": // Unique constraint violation
          return reply.status(409).header("Content-Type", "application/problem+json").send({
            type: "https://api.jaanify.com/errors/conflict",
            status: 409,
            title: "Conflict",
            detail: `A record with the given values already exists.`,
            instance: request.url,
          });

        case "P2003": // Foreign key constraint violation
          return reply.status(409).header("Content-Type", "application/problem+json").send({
            type: "https://api.jaanify.com/errors/conflict",
            status: 409,
            title: "Foreign Key Violation",
            detail: "Referenced record does not exist.",
            instance: request.url,
          });

        case "P2025": // Record not found
          return reply.status(404).header("Content-Type", "application/problem+json").send({
            type: "https://api.jaanify.com/errors/not-found",
            status: 404,
            title: "Not Found",
            detail: "The requested record was not found.",
            instance: request.url,
          });

        default:
          request.log.error({ err: error, code: error.code }, "Prisma error");
          break;
      }
    }

    // 4. Fastify built-in errors (404, etc.)
    if ("statusCode" in error && typeof error.statusCode === "number") {
      return reply
        .status(error.statusCode)
        .header("Content-Type", "application/problem+json")
        .send({
          type: `https://api.jaanify.com/errors/${error.statusCode}`,
          status: error.statusCode,
          title: error.message,
          instance: request.url,
        });
    }

    // 5. Fallback — unexpected errors
    request.log.error({ err: error, requestId }, "Unhandled error");
    return reply.status(500).header("Content-Type", "application/problem+json").send({
      type: "https://api.jaanify.com/errors/internal",
      status: 500,
      title: "Internal Server Error",
      detail: process.env.NODE_ENV === "production" ? undefined : error.message,
      instance: request.url,
    });
  });
}
