// Jaanify MVP — Zod Validation Schemas
// Generated by jaan.to backend-scaffold | 2026-02-09
// Derived from OpenAPI 3.1 contract (api.yaml)

import { z } from "zod";

// ── Shared ─────────────────────────────────────────

export const cursorParamSchema = z.object({
  cursor: z.string().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});

export const uuidParamSchema = z.object({
  task_id: z.string().uuid(),
});

export const planIdParamSchema = z.object({
  plan_id: z.string().uuid(),
});

export const slotIdParamSchema = z.object({
  plan_id: z.string().uuid(),
  slot_id: z.string().uuid(),
});

// ── Auth Schemas ───────────────────────────────────

export const googleAuthRequestSchema = z.object({
  code: z.string().min(1),
  redirect_uri: z.string().url(),
});
export type GoogleAuthRequest = z.infer<typeof googleAuthRequestSchema>;

export const registerRequestSchema = z.object({
  anonymous_id: z.string().min(1).max(64),
  provider: z.enum(["google", "email"]),
  code: z.string().min(1),
});
export type RegisterRequest = z.infer<typeof registerRequestSchema>;

export const authTokensSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string().optional(),
  token_type: z.literal("Bearer"),
  expires_in: z.number().int(),
});
export type AuthTokens = z.infer<typeof authTokensSchema>;

// ── User Schemas ───────────────────────────────────

export const userResponseSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email().nullable(),
  name: z.string().max(100).nullable(),
  avatar_url: z.string().url().nullable(),
  auth_provider: z.enum(["google", "email", "guest"]),
  preferences_json: z.record(z.unknown()).default({}),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});
export type UserResponse = z.infer<typeof userResponseSchema>;

export const userUpdateSchema = z.object({
  name: z.string().max(100).nullable().optional(),
  avatar_url: z.string().url().nullable().optional(),
  preferences_json: z.record(z.unknown()).optional(),
});
export type UserUpdate = z.infer<typeof userUpdateSchema>;

// ── Task Schemas ───────────────────────────────────

export const taskStatusEnum = z.enum(["active", "completed", "archived"]);
export const energyLevelEnum = z.enum(["low", "medium", "high"]).nullable();

export const taskCreateSchema = z.object({
  title: z.string().min(1).max(500),
  raw_input: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  deadline: z.string().datetime().nullable().optional(),
  category: z.string().max(100).nullable().optional(),
  energy_level: energyLevelEnum.optional(),
  estimated_minutes: z.number().int().min(1).nullable().optional(),
});
export type TaskCreate = z.infer<typeof taskCreateSchema>;

export const taskUpdateSchema = z.object({
  title: z.string().min(1).max(500).optional(),
  description: z.string().nullable().optional(),
  deadline: z.string().datetime().nullable().optional(),
  category: z.string().max(100).nullable().optional(),
  status: taskStatusEnum.optional(),
  energy_level: energyLevelEnum.optional(),
  estimated_minutes: z.number().int().min(1).nullable().optional(),
  priority_override: z.number().int().min(1).max(5).nullable().optional(),
});
export type TaskUpdate = z.infer<typeof taskUpdateSchema>;

export const taskListQuerySchema = cursorParamSchema.extend({
  status: taskStatusEnum.optional(),
  category: z.string().optional(),
});
export type TaskListQuery = z.infer<typeof taskListQuerySchema>;

export const taskParseRequestSchema = z.object({
  input: z.string().min(1).max(2000),
});
export type TaskParseRequest = z.infer<typeof taskParseRequestSchema>;

export const taskResponseSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  title: z.string(),
  raw_input: z.string().nullable(),
  description: z.string().nullable(),
  deadline: z.string().datetime().nullable(),
  category: z.string().nullable(),
  priority_score: z.number(),
  priority_override: z.number().int().nullable(),
  status: taskStatusEnum,
  reasoning_json: z.record(z.unknown()).nullable(),
  energy_level: energyLevelEnum,
  estimated_minutes: z.number().int().nullable(),
  completed_at: z.string().datetime().nullable(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});
export type TaskResponse = z.infer<typeof taskResponseSchema>;

export const taskParseResponseSchema = z.object({
  title: z.string(),
  deadline: z.string().datetime().nullable().optional(),
  category: z.string().nullable().optional(),
  energy_level: energyLevelEnum.optional(),
  estimated_minutes: z.number().int().nullable().optional(),
  confidence: z.number().min(0).max(1),
  reasoning: z.record(z.unknown()).optional(),
});
export type TaskParseResponse = z.infer<typeof taskParseResponseSchema>;

// ── Daily Plan Schemas ─────────────────────────────

export const dailyPlanSlotSchema = z.object({
  id: z.string().uuid(),
  plan_id: z.string().uuid(),
  task_id: z.string().uuid(),
  position: z.number().int().min(1),
  reasoning_json: z.record(z.unknown()).nullable(),
  status: z.enum(["pending", "completed", "skipped"]),
});
export type DailyPlanSlot = z.infer<typeof dailyPlanSlotSchema>;

export const dailyPlanSlotUpdateSchema = z.object({
  position: z.number().int().min(1).optional(),
  status: z.enum(["pending", "completed", "skipped"]).optional(),
});
export type DailyPlanSlotUpdate = z.infer<typeof dailyPlanSlotUpdateSchema>;

export const dailyPlanResponseSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  date: z.string(),
  status: z.enum(["generating", "active", "completed"]),
  reasoning_method: z.enum(["ai", "rule_based"]),
  generated_at: z.string().datetime().nullable(),
  slots: z.array(dailyPlanSlotSchema),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});
export type DailyPlanResponse = z.infer<typeof dailyPlanResponseSchema>;

// ── Feedback Schemas ───────────────────────────────

export const feedbackTypeEnum = z.enum([
  "priority_override",
  "plan_override",
  "not_now",
  "wrong_category",
  "other",
]);

export const feedbackCreateSchema = z.object({
  task_id: z.string().uuid().nullable().optional(),
  plan_id: z.string().uuid().nullable().optional(),
  feedback_type: feedbackTypeEnum,
  reason: z.string().max(500).nullable().optional(),
});
export type FeedbackCreate = z.infer<typeof feedbackCreateSchema>;

export const feedbackResponseSchema = z.object({
  id: z.string().uuid(),
  user_id: z.string().uuid(),
  task_id: z.string().uuid().nullable(),
  plan_id: z.string().uuid().nullable(),
  feedback_type: feedbackTypeEnum,
  reason: z.string().nullable(),
  created_at: z.string().datetime(),
});
export type FeedbackResponse = z.infer<typeof feedbackResponseSchema>;

// ── Guest Session Schemas ──────────────────────────

export const guestSessionCreateSchema = z.object({
  data_json: z.record(z.unknown()).optional(),
});
export type GuestSessionCreate = z.infer<typeof guestSessionCreateSchema>;

export const guestSessionResponseSchema = z.object({
  id: z.string().uuid(),
  anonymous_id: z.string(),
  data_json: z.record(z.unknown()),
  expires_at: z.string().datetime(),
  created_at: z.string().datetime(),
});
export type GuestSessionResponse = z.infer<typeof guestSessionResponseSchema>;

export const anonymousIdParamSchema = z.object({
  anonymous_id: z.string().max(64),
});

// ── RFC 9457 Problem Details ───────────────────────

export const problemDetailsSchema = z.object({
  type: z.string().url(),
  status: z.number().int(),
  title: z.string(),
  detail: z.string().nullable().optional(),
  instance: z.string().nullable().optional(),
});
export type ProblemDetails = z.infer<typeof problemDetailsSchema>;

export const validationProblemDetailsSchema = problemDetailsSchema.extend({
  errors: z.array(
    z.object({
      detail: z.string(),
      pointer: z.string(),
    })
  ),
});
export type ValidationProblemDetails = z.infer<typeof validationProblemDetailsSchema>;
