// Jaanify MVP — Configuration Files
// Generated by jaan.to backend-scaffold | 2026-02-09
// This file contains package.json, tsconfig.json, .env.example, and app.ts content

// ── package.json ───────────────────────────────────

export const packageJson = {
  name: "jaanify-api",
  version: "0.1.0",
  description: "Jaanify — AI Task Manager API (Fastify v5 + Prisma v6)",
  type: "module",
  engines: { node: ">=22.0.0" },
  scripts: {
    dev: "tsx watch src/server.ts",
    build: "tsc",
    start: "node --env-file=.env dist/server.js",
    lint: "eslint src/",
    test: "vitest run",
    "test:watch": "vitest",
    "db:generate": "prisma generate",
    "db:migrate:dev": "prisma migrate dev",
    "db:migrate:deploy": "prisma migrate deploy",
    "db:push": "prisma db push",
    "db:seed": "tsx prisma/seed.ts",
    "db:studio": "prisma studio",
    postinstall: "prisma generate",
  },
  dependencies: {
    fastify: "^5.7.0",
    "@fastify/autoload": "^6.0.0",
    "@fastify/cors": "^10.0.0",
    "@fastify/cookie": "^11.0.0",
    "@fastify/sensible": "^6.0.0",
    "@fastify/swagger": "^9.0.0",
    "@fastify/swagger-ui": "^5.0.0",
    "@prisma/client": "^6.0.0",
    "fastify-plugin": "^5.0.0",
    "fastify-type-provider-zod": "^6.1.0",
    zod: "^3.24.0",
  },
  devDependencies: {
    typescript: "^5.6.0",
    "@types/node": "^22.0.0",
    "fastify-tsconfig": "^2.0.0",
    prisma: "^6.0.0",
    tsx: "^4.0.0",
    vitest: "^2.0.0",
    eslint: "^9.0.0",
  },
};

// ── tsconfig.json ──────────────────────────────────

export const tsconfigJson = {
  extends: "fastify-tsconfig",
  compilerOptions: {
    target: "ES2023",
    module: "NodeNext",
    moduleResolution: "NodeNext",
    outDir: "dist",
    rootDir: "src",
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    resolveJsonModule: true,
    declaration: true,
    declarationMap: true,
    sourceMap: true,
  },
  include: ["src/**/*.ts"],
  exclude: ["node_modules", "dist", "prisma"],
};

// ── .env.example ───────────────────────────────────

export const envExample = `# Jaanify API — Environment Variables
# Copy to .env and fill in values

# Database
DATABASE_URL="postgresql://user:password@localhost:5432/jaanify?schema=public"

# Server
PORT=3000
HOST="0.0.0.0"
NODE_ENV="development"
LOG_LEVEL="info"

# CORS
CORS_ORIGIN="http://localhost:3001"

# Auth — Google OAuth2
GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET="YOUR_GOOGLE_CLIENT_SECRET"

# Auth — JWT
JWT_SECRET="YOUR_JWT_SECRET_MIN_32_CHARS"
JWT_EXPIRES_IN="1h"
REFRESH_TOKEN_SECRET="YOUR_REFRESH_SECRET_MIN_32_CHARS"
REFRESH_TOKEN_EXPIRES_IN="7d"

# Redis (Upstash)
REDIS_URL="redis://default:password@localhost:6379"

# OpenAI (for AI task parsing)
OPENAI_API_KEY="YOUR_OPENAI_API_KEY"
`;

// ── src/lib/env.ts — Zod Environment Validation ───

export const envValidationCode = `
import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().url(),
  PORT: z.coerce.number().int().default(3000),
  HOST: z.string().default("0.0.0.0"),
  NODE_ENV: z.enum(["development", "production", "test"]).default("development"),
  LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace"]).default("info"),
  CORS_ORIGIN: z.string().default("http://localhost:3001"),
  GOOGLE_CLIENT_ID: z.string().min(1),
  GOOGLE_CLIENT_SECRET: z.string().min(1),
  JWT_SECRET: z.string().min(32),
  JWT_EXPIRES_IN: z.string().default("1h"),
  REFRESH_TOKEN_SECRET: z.string().min(32),
  REFRESH_TOKEN_EXPIRES_IN: z.string().default("7d"),
  REDIS_URL: z.string().url().optional(),
  OPENAI_API_KEY: z.string().min(1),
});

export type Env = z.infer<typeof envSchema>;

export function validateEnv(): Env {
  const result = envSchema.safeParse(process.env);
  if (!result.success) {
    console.error("❌ Environment validation failed:");
    console.error(result.error.format());
    process.exit(1);
  }
  return result.data;
}
`;

// ── src/lib/prisma.ts — Prisma Singleton ──────────

export const prismaSingletonCode = `
import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "info", "warn", "error"]
        : ["error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
`;

// ── src/app.ts — Fastify App Factory ──────────────

export const appCode = `
import Fastify from "fastify";
import cors from "@fastify/cors";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import cookie from "@fastify/cookie";
import sensible from "@fastify/sensible";
import {
  serializerCompiler,
  validatorCompiler,
} from "fastify-type-provider-zod";
import { authMiddleware, errorHandlerPlugin } from "./plugins/middleware.js";
import { validateEnv } from "./lib/env.js";

export async function buildApp() {
  const env = validateEnv();

  const app = Fastify({
    logger: {
      level: env.LOG_LEVEL,
      transport:
        env.NODE_ENV === "development"
          ? { target: "pino-pretty" }
          : undefined,
    },
  });

  // Zod type provider
  app.setValidatorCompiler(validatorCompiler);
  app.setSerializerCompiler(serializerCompiler);

  // Plugins
  await app.register(cors, { origin: env.CORS_ORIGIN, credentials: true });
  await app.register(cookie);
  await app.register(sensible);
  await app.register(swagger, {
    openapi: {
      info: {
        title: "Jaanify API",
        version: "1.0.0",
        description: "AI Task Manager that shows its work",
      },
      servers: [{ url: \`http://\${env.HOST}:\${env.PORT}/v1\` }],
    },
  });
  await app.register(swaggerUi, { routePrefix: "/docs" });

  // Error handler (RFC 9457)
  await app.register(errorHandlerPlugin);

  // Auth middleware
  await app.register(authMiddleware);

  // Health check
  app.get("/v1/health", async () => ({ status: "ok", timestamp: new Date().toISOString() }));

  // Routes — register each resource under /v1 prefix
  // TODO: Import and register route modules from routes/ directory
  // await app.register(authRoutes, { prefix: "/v1" });
  // await app.register(userRoutes, { prefix: "/v1" });
  // await app.register(taskRoutes, { prefix: "/v1" });
  // await app.register(dailyPlanRoutes, { prefix: "/v1" });
  // await app.register(feedbackRoutes, { prefix: "/v1" });
  // await app.register(guestSessionRoutes, { prefix: "/v1" });

  return app;
}
`;

// ── src/server.ts — Entry Point ───────────────────

export const serverCode = `
import { buildApp } from "./app.js";
import { prisma } from "./lib/prisma.js";

async function start() {
  const app = await buildApp();
  const port = Number(process.env.PORT ?? 3000);
  const host = process.env.HOST ?? "0.0.0.0";

  try {
    await app.listen({ port, host });
    console.log(\`🚀 Jaanify API listening on http://\${host}:\${port}\`);
    console.log(\`📚 API docs: http://\${host}:\${port}/docs\`);
  } catch (err) {
    app.log.error(err);
    await prisma.$disconnect();
    process.exit(1);
  }

  // Graceful shutdown
  const signals: NodeJS.Signals[] = ["SIGINT", "SIGTERM"];
  for (const signal of signals) {
    process.on(signal, async () => {
      console.log(\`\\n\${signal} received, shutting down...\`);
      await app.close();
      await prisma.$disconnect();
      process.exit(0);
    });
  }
}

start();
`;
