// Jaanify MVP — TypeScript Interfaces from OpenAPI Contract
// Generated by jaan.to frontend-scaffold | 2026-02-09
// Source: jaan-to/outputs/dev/contract/01-jaanify-mvp/api.yaml
// DO NOT EDIT — regenerate with `pnpm generate:api`

// ── Shared Types ──────────────────────────────────

export interface Timestamps {
  created_at: string;
  updated_at: string;
}

export interface PaginationMeta {
  cursor: string | null;
  has_more: boolean;
  limit: number;
}

export interface ProblemDetails {
  type: string;
  status: number;
  title: string;
  detail?: string | null;
  instance?: string | null;
}

export interface ValidationError {
  detail: string;
  pointer: string;
}

export interface ValidationProblemDetails extends ProblemDetails {
  errors: ValidationError[];
}

// ── Auth Types ────────────────────────────────────

export interface GoogleAuthRequest {
  code: string;
  redirect_uri: string;
}

export interface AuthTokens {
  access_token: string;
  refresh_token: string;
  token_type: "Bearer";
  expires_in: number;
}

export interface RegisterRequest {
  anonymous_id: string;
  provider: "google" | "email";
  code: string;
}

// ── User Types ────────────────────────────────────

export type AuthProvider = "google" | "email" | "guest";

export interface User {
  id: string;
  email: string | null;
  name: string | null;
  avatar_url: string | null;
  auth_provider: AuthProvider;
  preferences_json: Record<string, unknown>;
}

export interface UserResponse extends User, Timestamps {}

export interface UserUpdate {
  name?: string | null;
  avatar_url?: string | null;
  preferences_json?: Record<string, unknown>;
}

// ── Task Types ────────────────────────────────────

export type TaskStatus = "active" | "completed" | "archived";
export type EnergyLevel = "low" | "medium" | "high";

export interface ReasoningJson {
  tier1: string;
  factors: Record<string, number>;
  confidence: number;
}

export interface Task {
  id: string;
  user_id: string;
  title: string;
  raw_input: string | null;
  description: string | null;
  deadline: string | null;
  category: string | null;
  priority_score: number;
  priority_override: number | null;
  status: TaskStatus;
  reasoning_json: ReasoningJson | null;
  energy_level: EnergyLevel | null;
  estimated_minutes: number | null;
  completed_at: string | null;
}

export interface TaskResponse extends Task, Timestamps {}

export interface TaskCreate {
  title: string;
  raw_input?: string | null;
  description?: string | null;
  deadline?: string | null;
  category?: string | null;
  energy_level?: EnergyLevel | null;
  estimated_minutes?: number | null;
}

export interface TaskUpdate {
  title?: string;
  description?: string | null;
  deadline?: string | null;
  category?: string | null;
  status?: TaskStatus;
  energy_level?: EnergyLevel | null;
  estimated_minutes?: number | null;
  priority_override?: number | null;
}

export interface TaskList {
  data: TaskResponse[];
  pagination: PaginationMeta;
}

export interface TaskParseRequest {
  input: string;
}

export interface TaskParseResponse {
  title: string;
  deadline: string | null;
  category: string | null;
  energy_level: EnergyLevel | null;
  estimated_minutes: number | null;
  confidence: number;
  reasoning: Record<string, string>;
}

// ── Daily Plan Types ──────────────────────────────

export type PlanStatus = "generating" | "active" | "completed";
export type ReasoningMethod = "ai" | "rule_based";
export type SlotStatus = "pending" | "completed" | "skipped";

export interface DailyPlanSlot {
  id: string;
  plan_id: string;
  task_id: string;
  position: number;
  reasoning_json: ReasoningJson | null;
  status: SlotStatus;
}

export interface DailyPlanSlotUpdate {
  position?: number;
  status?: SlotStatus;
}

export interface DailyPlan {
  id: string;
  user_id: string;
  date: string;
  status: PlanStatus;
  reasoning_method: ReasoningMethod;
  generated_at: string | null;
  slots: DailyPlanSlot[];
}

export interface DailyPlanResponse extends DailyPlan, Timestamps {}

export interface DailyPlanList {
  data: DailyPlanResponse[];
  pagination: PaginationMeta;
}

// ── Feedback Types ────────────────────────────────

export type FeedbackType =
  | "priority_override"
  | "plan_override"
  | "not_now"
  | "wrong_category"
  | "other";

export interface FeedbackCreate {
  task_id?: string | null;
  plan_id?: string | null;
  feedback_type: FeedbackType;
  reason?: string | null;
}

export interface FeedbackResponse {
  id: string;
  user_id: string;
  task_id: string | null;
  plan_id: string | null;
  feedback_type: FeedbackType;
  reason: string | null;
  created_at: string;
}

// ── Guest Session Types ───────────────────────────

export interface GuestSessionCreate {
  data_json?: Record<string, unknown>;
}

export interface GuestSessionResponse {
  id: string;
  anonymous_id: string;
  data_json: Record<string, unknown>;
  expires_at: string;
  created_at: string;
}

// ── Dashboard Derived Types ───────────────────────

export interface DashboardStats {
  tasks_completed_today: number;
  focus_minutes_today: number;
  streak_days: number;
}
