// Jaanify MVP — TanStack Query v5 Hooks + API Client
// Generated by jaan.to frontend-scaffold | 2026-02-09
// Source: OpenAPI contract (21 endpoints) + tech.md (TanStack Query v5)

import {
  useQuery,
  useMutation,
  useQueryClient,
  queryOptions,
  type UseQueryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";
import type {
  AuthTokens,
  GoogleAuthRequest,
  RegisterRequest,
  UserResponse,
  UserUpdate,
  TaskResponse,
  TaskCreate,
  TaskUpdate,
  TaskList,
  TaskParseRequest,
  TaskParseResponse,
  DailyPlanResponse,
  DailyPlanList,
  DailyPlanSlot,
  DailyPlanSlotUpdate,
  FeedbackCreate,
  FeedbackResponse,
  GuestSessionCreate,
  GuestSessionResponse,
} from "../types/api.js";
import { apiClient } from "../lib/api-client.js";

// ── Query Key Factories ───────────────────────────

export const queryKeys = {
  all: ["jaanify"] as const,
  user: () => [...queryKeys.all, "user"] as const,
  me: () => [...queryKeys.user(), "me"] as const,
  tasks: () => [...queryKeys.all, "tasks"] as const,
  taskList: (params?: { status?: string; category?: string; cursor?: string; limit?: number }) =>
    [...queryKeys.tasks(), "list", params] as const,
  taskDetail: (id: string) => [...queryKeys.tasks(), "detail", id] as const,
  taskParse: () => [...queryKeys.tasks(), "parse"] as const,
  plans: () => [...queryKeys.all, "plans"] as const,
  planList: (params?: { cursor?: string; limit?: number }) =>
    [...queryKeys.plans(), "list", params] as const,
  planDetail: (id: string) => [...queryKeys.plans(), "detail", id] as const,
  guest: () => [...queryKeys.all, "guest"] as const,
  guestSession: (anonymousId: string) =>
    [...queryKeys.guest(), anonymousId] as const,
} as const;

// ── Query Options Factories ───────────────────────

export const meQueryOptions = () =>
  queryOptions({
    queryKey: queryKeys.me(),
    queryFn: () => apiClient.get<UserResponse>("/users/me").then((r) => r.data),
  });

export const taskListQueryOptions = (params?: {
  status?: string;
  category?: string;
  cursor?: string;
  limit?: number;
}) =>
  queryOptions({
    queryKey: queryKeys.taskList(params),
    queryFn: () =>
      apiClient.get<TaskList>("/tasks", { params }).then((r) => r.data),
  });

export const taskDetailQueryOptions = (id: string) =>
  queryOptions({
    queryKey: queryKeys.taskDetail(id),
    queryFn: () =>
      apiClient.get<TaskResponse>(`/tasks/${id}`).then((r) => r.data),
    enabled: !!id,
  });

export const planListQueryOptions = (params?: {
  cursor?: string;
  limit?: number;
}) =>
  queryOptions({
    queryKey: queryKeys.planList(params),
    queryFn: () =>
      apiClient
        .get<DailyPlanList>("/daily-plans", { params })
        .then((r) => r.data),
  });

export const planDetailQueryOptions = (id: string) =>
  queryOptions({
    queryKey: queryKeys.planDetail(id),
    queryFn: () =>
      apiClient
        .get<DailyPlanResponse>(`/daily-plans/${id}`)
        .then((r) => r.data),
    enabled: !!id,
  });

export const guestSessionQueryOptions = (anonymousId: string) =>
  queryOptions({
    queryKey: queryKeys.guestSession(anonymousId),
    queryFn: () =>
      apiClient
        .get<GuestSessionResponse>(`/guest-sessions/${anonymousId}`)
        .then((r) => r.data),
    enabled: !!anonymousId,
  });

// ── Auth Hooks ────────────────────────────────────

export function useAuthGoogle(
  options?: UseMutationOptions<AuthTokens, Error, GoogleAuthRequest>
) {
  return useMutation({
    mutationFn: (data: GoogleAuthRequest) =>
      apiClient.post<AuthTokens>("/auth/google", data).then((r) => r.data),
    ...options,
  });
}

export function useAuthRefresh(
  options?: UseMutationOptions<AuthTokens, Error, void>
) {
  return useMutation({
    mutationFn: () =>
      apiClient.post<AuthTokens>("/auth/refresh").then((r) => r.data),
    ...options,
  });
}

export function useAuthRegister(
  options?: UseMutationOptions<AuthTokens, Error, RegisterRequest>
) {
  return useMutation({
    mutationFn: (data: RegisterRequest) =>
      apiClient.post<AuthTokens>("/auth/register", data).then((r) => r.data),
    ...options,
  });
}

export function useAuthLogout(
  options?: UseMutationOptions<void, Error, void>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => apiClient.delete("/auth/logout").then(() => undefined),
    onSuccess: () => {
      queryClient.clear();
    },
    ...options,
  });
}

// ── User Hooks ────────────────────────────────────

export function useGetMe(options?: Partial<UseQueryOptions<UserResponse>>) {
  return useQuery({
    ...meQueryOptions(),
    ...options,
  });
}

export function useUpdateMe(
  options?: UseMutationOptions<UserResponse, Error, UserUpdate>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: UserUpdate) =>
      apiClient.patch<UserResponse>("/users/me", data).then((r) => r.data),
    onSuccess: (data) => {
      queryClient.setQueryData(queryKeys.me(), data);
    },
    ...options,
  });
}

export function useDeleteMe(
  options?: UseMutationOptions<void, Error, void>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => apiClient.delete("/users/me").then(() => undefined),
    onSuccess: () => {
      queryClient.clear();
    },
    ...options,
  });
}

// ── Task Hooks ────────────────────────────────────

export function useListTasks(
  params?: { status?: string; category?: string; cursor?: string; limit?: number },
  options?: Partial<UseQueryOptions<TaskList>>
) {
  return useQuery({
    ...taskListQueryOptions(params),
    ...options,
  });
}

export function useGetTask(
  id: string,
  options?: Partial<UseQueryOptions<TaskResponse>>
) {
  return useQuery({
    ...taskDetailQueryOptions(id),
    ...options,
  });
}

export function useCreateTask(
  options?: UseMutationOptions<TaskResponse, Error, TaskCreate>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: TaskCreate) =>
      apiClient.post<TaskResponse>("/tasks", data).then((r) => r.data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.tasks() });
    },
    ...options,
  });
}

export function useUpdateTask(
  options?: UseMutationOptions<TaskResponse, Error, { id: string; data: TaskUpdate }>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: TaskUpdate }) =>
      apiClient.patch<TaskResponse>(`/tasks/${id}`, data).then((r) => r.data),
    onSuccess: (data, variables) => {
      queryClient.setQueryData(queryKeys.taskDetail(variables.id), data);
      queryClient.invalidateQueries({ queryKey: queryKeys.taskList() });
    },
    ...options,
  });
}

export function useDeleteTask(
  options?: UseMutationOptions<void, Error, string>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      apiClient.delete(`/tasks/${id}`).then(() => undefined),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.tasks() });
    },
    ...options,
  });
}

export function useParseTask(
  options?: UseMutationOptions<TaskParseResponse, Error, TaskParseRequest>
) {
  return useMutation({
    mutationFn: (data: TaskParseRequest) =>
      apiClient.post<TaskParseResponse>("/tasks/parse", data).then((r) => r.data),
    ...options,
  });
}

// ── Daily Plan Hooks ──────────────────────────────

export function useListDailyPlans(
  params?: { cursor?: string; limit?: number },
  options?: Partial<UseQueryOptions<DailyPlanList>>
) {
  return useQuery({
    ...planListQueryOptions(params),
    ...options,
  });
}

export function useGetDailyPlan(
  id: string,
  options?: Partial<UseQueryOptions<DailyPlanResponse>>
) {
  return useQuery({
    ...planDetailQueryOptions(id),
    ...options,
  });
}

export function useGenerateDailyPlan(
  options?: UseMutationOptions<DailyPlanResponse, Error, void>
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () =>
      apiClient
        .post<DailyPlanResponse>("/daily-plans/generate")
        .then((r) => r.data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.plans() });
    },
    ...options,
  });
}

export function useUpdatePlanSlot(
  options?: UseMutationOptions<
    DailyPlanSlot,
    Error,
    { planId: string; slotId: string; data: DailyPlanSlotUpdate }
  >
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      planId,
      slotId,
      data,
    }: {
      planId: string;
      slotId: string;
      data: DailyPlanSlotUpdate;
    }) =>
      apiClient
        .patch<DailyPlanSlot>(
          `/daily-plans/${planId}/slots/${slotId}`,
          data
        )
        .then((r) => r.data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({
        queryKey: queryKeys.planDetail(variables.planId),
      });
    },
    ...options,
  });
}

// ── Feedback Hooks ────────────────────────────────

export function useCreateFeedback(
  options?: UseMutationOptions<FeedbackResponse, Error, FeedbackCreate>
) {
  return useMutation({
    mutationFn: (data: FeedbackCreate) =>
      apiClient.post<FeedbackResponse>("/feedback", data).then((r) => r.data),
    ...options,
  });
}

// ── Guest Session Hooks ───────────────────────────

export function useCreateGuestSession(
  options?: UseMutationOptions<GuestSessionResponse, Error, GuestSessionCreate>
) {
  return useMutation({
    mutationFn: (data: GuestSessionCreate) =>
      apiClient
        .post<GuestSessionResponse>("/guest-sessions", data)
        .then((r) => r.data),
    ...options,
  });
}

export function useGetGuestSession(
  anonymousId: string,
  options?: Partial<UseQueryOptions<GuestSessionResponse>>
) {
  return useQuery({
    ...guestSessionQueryOptions(anonymousId),
    ...options,
  });
}
