// Jaanify MVP — React 19 Component Scaffolds
// Generated by jaan.to frontend-scaffold | 2026-02-09
// Stack: React 19 + Next.js 15 + TailwindCSS v4
// 26 components across 5 atomic design levels
//
// CONVENTIONS:
// - Server Components default; 'use client' only where interactivity needed
// - React 19: ref as prop (no forwardRef), no manual memo, no defaultProps
// - TailwindCSS v4: CSS-first config, suffix bang (bg-red-500!), bg-(--var)
// - All interactive elements: aria-*, keyboard nav, 44x44px touch targets
// - 4 states per data component: loading, error, empty, success

// ════════════════════════════════════════════
// ATOMS (8 components)
// ════════════════════════════════════════════

// ── 1. Button ─────────────────────────────
// File: src/components/atoms/Button.tsx
// 'use client' — interactive: click handlers, loading state

"use client";

import { type ButtonHTMLAttributes, type ReactNode } from "react";
import { cn } from "@/lib/cn";

type ButtonVariant = "primary" | "secondary" | "ghost" | "danger";
type ButtonSize = "sm" | "md" | "lg";

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  loading?: boolean;
  children: ReactNode;
  ref?: React.Ref<HTMLButtonElement>;
}

const variantStyles: Record<ButtonVariant, string> = {
  primary:
    "bg-(--color-sage) text-white hover:bg-(--color-sage-dark) active:scale-[0.98]",
  secondary:
    "bg-(--color-cream) text-(--color-text) border border-(--color-sage-light) hover:bg-(--color-sage-light)/10",
  ghost:
    "bg-transparent text-(--color-text) hover:bg-(--color-sage-light)/10",
  danger:
    "bg-(--color-terracotta) text-white hover:bg-(--color-terracotta-dark) active:scale-[0.98]",
};

const sizeStyles: Record<ButtonSize, string> = {
  sm: "px-3 py-1.5 text-sm min-h-[36px]",
  md: "px-4 py-2 text-base min-h-[44px]",
  lg: "px-6 py-3 text-lg min-h-[48px]",
};

export function Button({
  variant = "primary",
  size = "md",
  loading = false,
  disabled,
  className,
  children,
  ref,
  ...props
}: ButtonProps) {
  return (
    <button
      ref={ref}
      disabled={disabled || loading}
      className={cn(
        "inline-flex items-center justify-center gap-2 rounded-lg font-medium",
        "transition-all duration-150 ease-out",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--color-sage) focus-visible:ring-offset-2",
        "disabled:opacity-50 disabled:cursor-not-allowed",
        "motion-reduce:transition-none",
        variantStyles[variant],
        sizeStyles[size],
        className
      )}
      {...props}
    >
      {loading ? (
        <>
          <span
            className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent"
            aria-hidden="true"
          />
          <span className="sr-only">Loading...</span>
        </>
      ) : (
        children
      )}
    </button>
  );
}

// ── 2. IconButton ─────────────────────────
// File: src/components/atoms/IconButton.tsx
// 'use client' — interactive: click handlers

interface IconButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  label: string;
  size?: "sm" | "md" | "lg";
  variant?: "default" | "circle";
  ref?: React.Ref<HTMLButtonElement>;
}

const iconSizeStyles = {
  sm: "h-8 w-8",
  md: "h-11 w-11",
  lg: "h-14 w-14",
};

export function IconButton({
  label,
  size = "md",
  variant = "default",
  className,
  children,
  ref,
  ...props
}: IconButtonProps) {
  return (
    <button
      ref={ref}
      aria-label={label}
      className={cn(
        "inline-flex items-center justify-center",
        "transition-all duration-150 ease-out",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--color-sage) focus-visible:ring-offset-2",
        "hover:bg-(--color-sage-light)/10 active:scale-[0.95]",
        "disabled:opacity-50 disabled:cursor-not-allowed",
        "motion-reduce:transition-none",
        iconSizeStyles[size],
        variant === "circle" ? "rounded-full" : "rounded-lg",
        className
      )}
      {...props}
    >
      {children}
    </button>
  );
}

// ── 3. TextInput ──────────────────────────
// File: src/components/atoms/TextInput.tsx
// 'use client' — interactive: input handling, auto-resize

import { type InputHTMLAttributes, type TextareaHTMLAttributes, useId } from "react";

interface TextInputProps {
  label: string;
  error?: string;
  multiline?: boolean;
  ref?: React.Ref<HTMLInputElement | HTMLTextAreaElement>;
  inputProps?: InputHTMLAttributes<HTMLInputElement>;
  textareaProps?: TextareaHTMLAttributes<HTMLTextAreaElement>;
}

export function TextInput({
  label,
  error,
  multiline = false,
  ref,
  inputProps,
  textareaProps,
}: TextInputProps) {
  const id = useId();
  const errorId = `${id}-error`;

  const sharedClasses = cn(
    "w-full bg-transparent px-0 py-2 text-(--color-text)",
    "border-0 border-b-2 border-(--color-sage-light)/30",
    "placeholder:text-(--color-text)/40",
    "focus:border-(--color-sage) focus:outline-none",
    "transition-colors duration-150",
    "motion-reduce:transition-none",
    error && "border-(--color-terracotta) focus:border-(--color-terracotta)"
  );

  return (
    <div className="flex flex-col gap-1">
      <label htmlFor={id} className="text-sm font-medium text-(--color-text)/70">
        {label}
      </label>
      {multiline ? (
        <textarea
          ref={ref as React.Ref<HTMLTextAreaElement>}
          id={id}
          aria-invalid={!!error}
          aria-describedby={error ? errorId : undefined}
          className={cn(sharedClasses, "resize-none")}
          rows={1}
          {...textareaProps}
        />
      ) : (
        <input
          ref={ref as React.Ref<HTMLInputElement>}
          id={id}
          aria-invalid={!!error}
          aria-describedby={error ? errorId : undefined}
          className={sharedClasses}
          {...inputProps}
        />
      )}
      {error && (
        <p id={errorId} className="text-sm text-(--color-terracotta)" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}

// ── 4. Checkbox ───────────────────────────
// File: src/components/atoms/Checkbox.tsx
// 'use client' — interactive: toggle state

interface CheckboxProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  disabled?: boolean;
}

export function Checkbox({ label, checked, onChange, disabled = false }: CheckboxProps) {
  const id = useId();

  return (
    <div className="flex items-center gap-3">
      <input
        type="checkbox"
        id={id}
        checked={checked}
        disabled={disabled}
        onChange={(e) => onChange(e.target.checked)}
        className={cn(
          "h-5 w-5 rounded border-2 border-(--color-sage-light)/40",
          "checked:bg-(--color-sage) checked:border-(--color-sage)",
          "focus-visible:ring-2 focus-visible:ring-(--color-sage) focus-visible:ring-offset-2",
          "transition-all duration-150",
          "motion-reduce:transition-none",
          "cursor-pointer disabled:cursor-not-allowed disabled:opacity-50"
        )}
      />
      <label
        htmlFor={id}
        className={cn(
          "text-(--color-text) cursor-pointer select-none",
          "transition-all duration-150",
          checked && "line-through opacity-60"
        )}
      >
        {label}
      </label>
    </div>
  );
}

// ── 5. Badge ──────────────────────────────
// File: src/components/atoms/Badge.tsx
// Server Component — no interactivity

type BadgeVariant = "high" | "medium" | "low" | "default";

interface BadgeProps {
  variant?: BadgeVariant;
  children: ReactNode;
}

const badgeVariantStyles: Record<BadgeVariant, string> = {
  high: "bg-(--color-terracotta)/15 text-(--color-terracotta)",
  medium: "bg-(--color-gold)/15 text-(--color-gold-dark)",
  low: "bg-(--color-sage)/15 text-(--color-sage)",
  default: "bg-(--color-sage-light)/15 text-(--color-text)/70",
};

export function Badge({ variant = "default", children }: BadgeProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium",
        badgeVariantStyles[variant]
      )}
    >
      {children}
    </span>
  );
}

// ── 6. Chip ───────────────────────────────
// File: src/components/atoms/Chip.tsx
// 'use client' — interactive variant has click handler

interface ChipProps {
  label: string;
  onClick?: () => void;
  active?: boolean;
  removable?: boolean;
  onRemove?: () => void;
}

export function Chip({
  label,
  onClick,
  active = false,
  removable = false,
  onRemove,
}: ChipProps) {
  const isInteractive = !!onClick;

  return (
    <span
      role={isInteractive ? "button" : undefined}
      tabIndex={isInteractive ? 0 : undefined}
      onClick={onClick}
      onKeyDown={(e) => {
        if (isInteractive && (e.key === "Enter" || e.key === " ")) {
          e.preventDefault();
          onClick?.();
        }
      }}
      className={cn(
        "inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm",
        "transition-all duration-150",
        "motion-reduce:transition-none",
        isInteractive && "cursor-pointer hover:bg-(--color-sage)/20",
        isInteractive &&
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--color-sage)",
        active
          ? "bg-(--color-sage)/20 text-(--color-sage) font-medium"
          : "bg-(--color-cream-dark)/50 text-(--color-text)/70"
      )}
    >
      {label}
      {removable && onRemove && (
        <button
          onClick={(e) => {
            e.stopPropagation();
            onRemove();
          }}
          aria-label={`Remove ${label}`}
          className="ml-0.5 h-4 w-4 rounded-full hover:bg-(--color-terracotta)/20 inline-flex items-center justify-center"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      )}
    </span>
  );
}

// ── 7. ProgressDots ───────────────────────
// File: src/components/atoms/ProgressDots.tsx
// 'use client' — animated active state

interface ProgressDotsProps {
  totalSteps: number;
  currentStep: number;
}

export function ProgressDots({ totalSteps, currentStep }: ProgressDotsProps) {
  return (
    <div className="flex items-center justify-center gap-2" role="group" aria-label="Progress">
      {Array.from({ length: totalSteps }, (_, i) => (
        <div
          key={i}
          role="presentation"
          aria-current={i === currentStep ? "step" : undefined}
          className={cn(
            "h-2 rounded-full transition-all duration-300 ease-out",
            "motion-reduce:transition-none",
            i === currentStep
              ? "w-6 bg-(--color-sage)"
              : "w-2 bg-(--color-sage-light)/30"
          )}
        />
      ))}
      <span className="sr-only">
        Step {currentStep + 1} of {totalSteps}
      </span>
    </div>
  );
}

// ── 8. Skeleton ───────────────────────────
// File: src/components/atoms/Skeleton.tsx
// Server Component — CSS animation only

interface SkeletonProps {
  className?: string;
  variant?: "text" | "circular" | "rectangular";
}

export function Skeleton({ className, variant = "text" }: SkeletonProps) {
  return (
    <div
      aria-hidden="true"
      className={cn(
        "animate-pulse bg-gradient-to-r from-(--color-cream) via-(--color-cream-dark)/50 to-(--color-cream)",
        "motion-reduce:animate-none motion-reduce:bg-(--color-cream-dark)/30",
        variant === "text" && "h-4 w-full rounded",
        variant === "circular" && "rounded-full",
        variant === "rectangular" && "rounded-lg",
        className
      )}
    />
  );
}

// ════════════════════════════════════════════
// MOLECULES (7 components)
// ════════════════════════════════════════════

// ── 9. ParsedField ────────────────────────
// File: src/components/molecules/ParsedField.tsx
// 'use client' — interactive: inline edit toggle

import { useState } from "react";

interface ParsedFieldProps {
  icon: ReactNode;
  label: string;
  value: string;
  onEdit: (newValue: string) => void;
}

export function ParsedField({ icon, label, value, onEdit }: ParsedFieldProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editValue, setEditValue] = useState(value);
  const fieldId = useId();

  const handleSave = () => {
    onEdit(editValue);
    setIsEditing(false);
  };

  return (
    <div className="flex items-center gap-3 py-2">
      <span className="text-(--color-sage) flex-shrink-0" aria-hidden="true">
        {icon}
      </span>
      <div className="flex-1 min-w-0">
        <span className="text-xs text-(--color-text)/50 uppercase tracking-wide">
          {label}
        </span>
        {isEditing ? (
          <input
            id={fieldId}
            type="text"
            value={editValue}
            onChange={(e) => setEditValue(e.target.value)}
            onBlur={handleSave}
            onKeyDown={(e) => {
              if (e.key === "Enter") handleSave();
              if (e.key === "Escape") {
                setEditValue(value);
                setIsEditing(false);
              }
            }}
            className="block w-full bg-transparent border-b border-(--color-sage) text-(--color-text) focus:outline-none py-0.5"
            autoFocus
            aria-label={`Edit ${label}`}
          />
        ) : (
          <p className="text-(--color-text) truncate">{value}</p>
        )}
      </div>
      {!isEditing && (
        <IconButton
          label={`Edit ${label}`}
          size="sm"
          onClick={() => setIsEditing(true)}
        >
          <svg
            className="h-4 w-4 text-(--color-text)/40"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
          </svg>
        </IconButton>
      )}
    </div>
  );
}

// ── 10. ReasoningTier1 ────────────────────
// File: src/components/molecules/ReasoningTier1.tsx
// 'use client' — interactive: expand trigger

interface ReasoningTier1Props {
  summary: string;
  isExpanded: boolean;
  onToggle: () => void;
  expandLabel?: string;
}

export function ReasoningTier1({
  summary,
  isExpanded,
  onToggle,
  expandLabel = "See why",
}: ReasoningTier1Props) {
  return (
    <button
      onClick={onToggle}
      aria-expanded={isExpanded}
      className={cn(
        "w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left",
        "text-sm text-(--color-text)/70",
        "hover:bg-(--color-sage-light)/10 transition-colors duration-150",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--color-sage)",
        "motion-reduce:transition-none"
      )}
    >
      <svg
        className="h-4 w-4 text-(--color-sage) flex-shrink-0"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={2}
      >
        <path d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
      </svg>
      <span className="flex-1 truncate">{summary}</span>
      <svg
        className={cn(
          "h-4 w-4 text-(--color-text)/40 transition-transform duration-200",
          isExpanded && "rotate-180"
        )}
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        strokeWidth={2}
      >
        <path d="M19 9l-7 7-7-7" />
      </svg>
      <span className="sr-only">{isExpanded ? "Collapse reasoning" : expandLabel}</span>
    </button>
  );
}

// ── 11. SuggestionChips ───────────────────
// File: src/components/molecules/SuggestionChips.tsx
// 'use client' — interactive: click fills input

interface SuggestionChipsProps {
  suggestions: string[];
  onSelect: (suggestion: string) => void;
}

export function SuggestionChips({ suggestions, onSelect }: SuggestionChipsProps) {
  return (
    <div
      className="flex gap-2 overflow-x-auto pb-2 scrollbar-none"
      role="group"
      aria-label="Suggestion chips"
    >
      {suggestions.map((suggestion) => (
        <Chip
          key={suggestion}
          label={suggestion}
          onClick={() => onSelect(suggestion)}
        />
      ))}
    </div>
  );
}

// ── 12. StatCard ──────────────────────────
// File: src/components/molecules/StatCard.tsx
// Server Component — display only

interface StatCardProps {
  icon: ReactNode;
  value: string | number;
  label: string;
}

export function StatCard({ icon, value, label }: StatCardProps) {
  return (
    <div className="flex flex-col items-center gap-1 rounded-xl bg-(--color-cream) p-4 min-w-[100px]">
      <span className="text-(--color-sage)" aria-hidden="true">
        {icon}
      </span>
      <span className="text-2xl font-bold text-(--color-text)">{value}</span>
      <span className="text-xs text-(--color-text)/60">{label}</span>
    </div>
  );
}

// ── 13. VoiceFAB ──────────────────────────
// File: src/components/molecules/VoiceFAB.tsx
// 'use client' — interactive: Web Speech API, media permissions

type VoiceFABState = "idle" | "listening" | "processing" | "error" | "unsupported";

interface VoiceFABProps {
  state: VoiceFABState;
  onPress: () => void;
  onStop: () => void;
}

export function VoiceFAB({ state, onPress, onStop }: VoiceFABProps) {
  if (state === "unsupported") return null;

  const isListening = state === "listening";
  const isProcessing = state === "processing";

  return (
    <button
      onClick={isListening ? onStop : onPress}
      disabled={isProcessing}
      aria-label={
        isListening
          ? "Stop voice recording"
          : isProcessing
            ? "Processing voice input"
            : state === "error"
              ? "Retry voice input"
              : "Start voice input"
      }
      className={cn(
        "fixed bottom-6 right-6 z-50",
        "h-14 w-14 rounded-full shadow-lg",
        "flex items-center justify-center",
        "transition-all duration-200 ease-out",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-(--color-sage) focus-visible:ring-offset-2",
        "motion-reduce:transition-none",
        isListening
          ? "bg-(--color-terracotta) text-white animate-pulse"
          : "bg-(--color-sage) text-white hover:bg-(--color-sage-dark)",
        isProcessing && "opacity-70 cursor-wait",
        state === "error" && "bg-(--color-terracotta)"
      )}
    >
      {isProcessing ? (
        <span className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent" />
      ) : (
        <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
        </svg>
      )}
      {isListening && (
        <span className="absolute inset-0 rounded-full border-2 border-(--color-terracotta) animate-ping motion-reduce:animate-none" />
      )}
    </button>
  );
}

// ── 14. ActionButtons ─────────────────────
// File: src/components/molecules/ActionButtons.tsx
// 'use client' — interactive: staggered animation, click handlers

interface ActionButtonsProps {
  onCancel: () => void;
  onSave: () => void;
  saveLabel?: string;
  cancelLabel?: string;
  saving?: boolean;
  disabled?: boolean;
}

export function ActionButtons({
  onCancel,
  onSave,
  saveLabel = "Save Task",
  cancelLabel = "Cancel",
  saving = false,
  disabled = false,
}: ActionButtonsProps) {
  return (
    <div className="flex gap-3 animate-in slide-in-from-bottom-2 motion-reduce:animate-none">
      <Button
        variant="ghost"
        onClick={onCancel}
        disabled={saving}
        className="flex-1"
      >
        {cancelLabel}
      </Button>
      <Button
        variant="primary"
        onClick={onSave}
        loading={saving}
        disabled={disabled}
        className="flex-1"
      >
        {saveLabel}
      </Button>
    </div>
  );
}

// ── 15. PlanTaskRow ───────────────────────
// File: src/components/molecules/PlanTaskRow.tsx
// 'use client' — interactive: expand reasoning

import type { DailyPlanSlot, TaskResponse, ReasoningJson } from "@/types/api";

interface PlanTaskRowProps {
  slot: DailyPlanSlot;
  task: TaskResponse;
  onToggleReasoning: () => void;
  reasoningExpanded: boolean;
}

export function PlanTaskRow({
  slot,
  task,
  onToggleReasoning,
  reasoningExpanded,
}: PlanTaskRowProps) {
  return (
    <div className="flex items-start gap-3 py-3 border-b border-(--color-sage-light)/10 last:border-0">
      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-(--color-sage)/15 text-(--color-sage) text-xs font-bold flex items-center justify-center">
        {slot.position}
      </span>
      <div className="flex-1 min-w-0">
        <p className="text-(--color-text) font-medium truncate">{task.title}</p>
        {task.estimated_minutes && (
          <span className="text-xs text-(--color-text)/50">
            ~{task.estimated_minutes}min
          </span>
        )}
        {slot.reasoning_json && (
          <ReasoningTier1
            summary={slot.reasoning_json.tier1}
            isExpanded={reasoningExpanded}
            onToggle={onToggleReasoning}
          />
        )}
      </div>
    </div>
  );
}

// ════════════════════════════════════════════
// ORGANISMS (6 components)
// ════════════════════════════════════════════

// ── 16. ReasoningCard ─────────────────────
// File: src/components/organisms/ReasoningCard.tsx
// 'use client' — interactive: 3-tier progressive disclosure, data fetch

type ReasoningCardState =
  | "collapsed"
  | "tier2_expanded"
  | "tier3_expanded"
  | "loading"
  | "error";

interface ReasoningCardProps {
  reasoning: ReasoningJson;
  onOverride?: (reason: string) => void;
  onFetchTier3?: () => Promise<{ chain: string[]; accuracy: number }>;
}

export function ReasoningCard({
  reasoning,
  onOverride,
  onFetchTier3,
}: ReasoningCardProps) {
  const [state, setState] = useState<ReasoningCardState>("collapsed");
  const [tier3Data, setTier3Data] = useState<{
    chain: string[];
    accuracy: number;
  } | null>(null);

  const handleToggleTier2 = () => {
    setState((s) => (s === "collapsed" ? "tier2_expanded" : "collapsed"));
  };

  const handleToggleTier3 = async () => {
    if (state === "tier3_expanded") {
      setState("tier2_expanded");
      return;
    }
    if (!onFetchTier3) return;
    setState("loading");
    try {
      const data = await onFetchTier3();
      setTier3Data(data);
      setState("tier3_expanded");
    } catch {
      setState("error");
    }
  };

  return (
    <div className="rounded-xl border border-(--color-sage-light)/20 bg-(--color-cream)/50 overflow-hidden">
      {/* Tier 1: One-line summary */}
      <ReasoningTier1
        summary={reasoning.tier1}
        isExpanded={state !== "collapsed"}
        onToggle={handleToggleTier2}
      />

      {/* Tier 2: Factor weights */}
      {(state === "tier2_expanded" || state === "tier3_expanded") && (
        <div className="px-4 pb-3 space-y-3" aria-label="Reasoning factors">
          <div className="space-y-2">
            {Object.entries(reasoning.factors).map(([factor, weight]) => (
              <div key={factor} className="flex items-center gap-2">
                <span className="text-xs text-(--color-text)/60 w-24 truncate capitalize">
                  {factor.replace(/_/g, " ")}
                </span>
                <div className="flex-1 h-2 bg-(--color-sage-light)/20 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-(--color-sage) rounded-full transition-all duration-500 motion-reduce:transition-none"
                    style={{ width: `${weight * 100}%` }}
                  />
                </div>
                <span className="text-xs text-(--color-text)/50 w-10 text-right">
                  {Math.round(weight * 100)}%
                </span>
              </div>
            ))}
          </div>
          <div className="flex items-center justify-between pt-1">
            <span className="text-xs text-(--color-sage)">
              Confidence: {Math.round(reasoning.confidence * 100)}%
            </span>
            <div className="flex gap-2">
              {onOverride && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onOverride("not_now")}
                >
                  Not now
                </Button>
              )}
              {onFetchTier3 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleToggleTier3}
                >
                  {state === "tier3_expanded"
                    ? "Less detail"
                    : "See full reasoning"}
                </Button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Tier 3: Full audit */}
      {state === "tier3_expanded" && tier3Data && (
        <div className="px-4 pb-4 border-t border-(--color-sage-light)/10 pt-3">
          <h4 className="text-xs font-medium text-(--color-text)/60 mb-2 uppercase tracking-wide">
            Reasoning Chain
          </h4>
          <ol className="space-y-1 list-decimal list-inside text-sm text-(--color-text)/80">
            {tier3Data.chain.map((step, i) => (
              <li key={i}>{step}</li>
            ))}
          </ol>
          <p className="mt-2 text-xs text-(--color-text)/50">
            Historical accuracy: {Math.round(tier3Data.accuracy * 100)}%
          </p>
        </div>
      )}

      {/* Loading state */}
      {state === "loading" && (
        <div className="px-4 pb-3 space-y-2">
          <Skeleton className="h-3 w-3/4" />
          <Skeleton className="h-3 w-1/2" />
        </div>
      )}

      {/* Error state */}
      {state === "error" && (
        <div className="px-4 pb-3">
          <p className="text-sm text-(--color-terracotta)">
            Reasoning unavailable.{" "}
            <button
              onClick={handleToggleTier3}
              className="underline hover:no-underline"
            >
              Retry
            </button>
          </p>
        </div>
      )}
    </div>
  );
}

// ── 17. TaskCard ──────────────────────────
// File: src/components/organisms/TaskCard.tsx
// 'use client' — interactive: completion toggle, reasoning expand

interface TaskCardProps {
  task: TaskResponse;
  onComplete: (id: string) => void;
  onOverride?: (id: string, reason: string) => void;
}

export function TaskCard({ task, onComplete, onOverride }: TaskCardProps) {
  const isCompleted = task.status === "completed";
  const priorityVariant =
    task.priority_score >= 0.7
      ? "high"
      : task.priority_score >= 0.4
        ? "medium"
        : "low";

  return (
    <article
      className={cn(
        "rounded-xl border-l-4 bg-(--color-cream)/50 p-4",
        "transition-all duration-200",
        "motion-reduce:transition-none",
        priorityVariant === "high" && "border-l-(--color-terracotta)",
        priorityVariant === "medium" && "border-l-(--color-gold)",
        priorityVariant === "low" && "border-l-(--color-sage)",
        isCompleted && "opacity-60"
      )}
    >
      <div className="flex items-start gap-3">
        <Checkbox
          label=""
          checked={isCompleted}
          onChange={() => onComplete(task.id)}
        />
        <div className="flex-1 min-w-0">
          <h3
            className={cn(
              "font-medium text-(--color-text)",
              isCompleted && "line-through"
            )}
            title={task.title.length > 60 ? task.title : undefined}
          >
            {task.title}
          </h3>
          <div className="flex items-center gap-2 mt-1">
            {task.category && <Badge variant="default">{task.category}</Badge>}
            {task.estimated_minutes && (
              <span className="text-xs text-(--color-text)/50">
                ~{task.estimated_minutes}min
              </span>
            )}
            {task.energy_level && (
              <Badge
                variant={
                  task.energy_level === "high"
                    ? "high"
                    : task.energy_level === "medium"
                      ? "medium"
                      : "low"
                }
              >
                {task.energy_level}
              </Badge>
            )}
          </div>
        </div>
      </div>
      {task.reasoning_json && !isCompleted && (
        <div className="mt-3">
          <ReasoningCard
            reasoning={task.reasoning_json}
            onOverride={
              onOverride
                ? (reason) => onOverride(task.id, reason)
                : undefined
            }
          />
        </div>
      )}
    </article>
  );
}

// ── 18. DailyPlan ─────────────────────────
// File: src/components/organisms/DailyPlan.tsx
// 'use client' — interactive: data fetching states, slot expansion

type DailyPlanState =
  | "loading"
  | "success"
  | "error"
  | "empty"
  | "refreshing";

interface DailyPlanComponentProps {
  plan: DailyPlanResponse | null;
  tasks: Map<string, TaskResponse>;
  state: DailyPlanState;
  onGenerate: () => void;
  onAddTask: () => void;
  onRefresh: () => void;
}

export function DailyPlanComponent({
  plan,
  tasks,
  state,
  onGenerate,
  onAddTask,
  onRefresh,
}: DailyPlanComponentProps) {
  const [expandedSlot, setExpandedSlot] = useState<string | null>(null);

  // Loading state
  if (state === "loading") {
    return (
      <section className="space-y-4" aria-label="Daily plan loading">
        <div className="rounded-xl bg-(--color-cream)/50 p-4 space-y-3">
          <p className="text-sm text-(--color-sage) animate-pulse motion-reduce:animate-none">
            AI is planning your day...
          </p>
          <Skeleton className="h-12 w-full" variant="rectangular" />
          <Skeleton className="h-12 w-full" variant="rectangular" />
          <Skeleton className="h-12 w-full" variant="rectangular" />
        </div>
      </section>
    );
  }

  // Empty state
  if (state === "empty") {
    return (
      <section className="rounded-xl bg-(--color-cream)/50 p-8 text-center" aria-label="No tasks">
        <div className="text-4xl mb-3" aria-hidden="true">
          {/* Placeholder for illustration */}
          <span className="text-(--color-sage-light)">&#9728;</span>
        </div>
        <h2 className="text-lg font-medium text-(--color-text) mb-2">
          No tasks for today
        </h2>
        <p className="text-sm text-(--color-text)/60 mb-4">
          Add your first task and let AI plan your day
        </p>
        <Button variant="primary" onClick={onAddTask}>
          Add a task
        </Button>
      </section>
    );
  }

  // Error state
  if (state === "error") {
    return (
      <section className="rounded-xl bg-(--color-cream)/50 p-6" aria-label="Plan error">
        <p className="text-sm text-(--color-terracotta) mb-3">
          Couldn&apos;t generate your daily plan.
        </p>
        <Button variant="secondary" onClick={onRefresh}>
          Try again
        </Button>
      </section>
    );
  }

  // Success state
  return (
    <section
      className="space-y-4"
      aria-label="Today's plan"
    >
      {state === "refreshing" && (
        <div className="text-xs text-(--color-sage) animate-pulse motion-reduce:animate-none">
          Updating plan...
        </div>
      )}
      <div className="rounded-xl bg-(--color-cream)/50 p-4">
        <h2 className="text-sm font-medium text-(--color-text)/60 mb-3 uppercase tracking-wide">
          Today&apos;s Plan
        </h2>
        {plan?.slots.map((slot) => {
          const task = tasks.get(slot.task_id);
          if (!task) return null;
          return (
            <PlanTaskRow
              key={slot.id}
              slot={slot}
              task={task}
              reasoningExpanded={expandedSlot === slot.id}
              onToggleReasoning={() =>
                setExpandedSlot((s) => (s === slot.id ? null : slot.id))
              }
            />
          );
        })}
      </div>
    </section>
  );
}

// ── 19. TaskInputForm ─────────────────────
// File: src/components/organisms/TaskInputForm.tsx
// 'use client' — interactive: debounced input, voice, state machine

import { useCallback, useEffect, useRef } from "react";
import type { TaskParseResponse } from "@/types/api";

type TaskInputState =
  | "idle"
  | "typing"
  | "parsing"
  | "parsed"
  | "saving"
  | "error"
  | "voice_listening"
  | "voice_processing";

interface TaskInputFormProps {
  onSave: (data: {
    title: string;
    raw_input: string;
    parsed: TaskParseResponse | null;
  }) => void;
  onCancel: () => void;
  onParse: (input: string) => Promise<TaskParseResponse>;
  initialText?: string;
  suggestions?: string[];
}

export function TaskInputForm({
  onSave,
  onCancel,
  onParse,
  initialText = "",
  suggestions = ["Call...", "Remind me...", "Review...", "Buy..."],
}: TaskInputFormProps) {
  const [inputState, setInputState] = useState<TaskInputState>("idle");
  const [text, setText] = useState(initialText);
  const [parsed, setParsed] = useState<TaskParseResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout>>();

  // Auto-resize textarea
  const autoResize = useCallback(() => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = "auto";
      el.style.height = `${el.scrollHeight}px`;
    }
  }, []);

  // Debounced parse
  useEffect(() => {
    if (text.length < 4 || inputState === "saving") return;
    clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      setInputState("parsing");
      try {
        const result = await onParse(text);
        setParsed(result);
        setInputState("parsed");
      } catch {
        setError("Couldn't parse your input. You can still save manually.");
        setInputState("error");
      }
    }, 600);
    return () => clearTimeout(debounceRef.current);
  }, [text, onParse, inputState]);

  const handleTextChange = (value: string) => {
    setText(value);
    setInputState("typing");
    setError(null);
    autoResize();
  };

  const handleSave = () => {
    if (!text.trim()) return;
    setInputState("saving");
    onSave({
      title: parsed?.title ?? text.trim(),
      raw_input: text,
      parsed,
    });
  };

  const handleSuggestion = (suggestion: string) => {
    setText(suggestion);
    textareaRef.current?.focus();
    handleTextChange(suggestion);
  };

  return (
    <div className="flex flex-col gap-6 max-w-lg mx-auto px-4">
      {/* Suggestion chips — hide when typing */}
      {inputState === "idle" && (
        <SuggestionChips
          suggestions={suggestions}
          onSelect={handleSuggestion}
        />
      )}

      {/* Text input */}
      <div className="relative">
        <textarea
          ref={textareaRef}
          value={text}
          onChange={(e) => handleTextChange(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !e.shiftKey && parsed) {
              e.preventDefault();
              handleSave();
            }
          }}
          placeholder="What do you need to do?"
          className={cn(
            "w-full bg-transparent border-0 border-b-2 border-(--color-sage-light)/30",
            "text-xl text-(--color-text) placeholder:text-(--color-text)/30",
            "focus:border-(--color-sage) focus:outline-none",
            "resize-none overflow-hidden py-3",
            "transition-colors duration-150",
            "motion-reduce:transition-none"
          )}
          rows={1}
          autoFocus
          aria-label="Task description"
        />
        {inputState === "parsing" && (
          <div
            className="flex gap-1.5 mt-2"
            role="status"
            aria-label="Parsing your input"
          >
            <span className="h-1.5 w-1.5 rounded-full bg-(--color-sage) animate-bounce [animation-delay:0ms]" />
            <span className="h-1.5 w-1.5 rounded-full bg-(--color-sage) animate-bounce [animation-delay:150ms]" />
            <span className="h-1.5 w-1.5 rounded-full bg-(--color-sage) animate-bounce [animation-delay:300ms]" />
          </div>
        )}
      </div>

      {/* Parsed result */}
      {inputState === "parsed" && parsed && (
        <div className="rounded-xl border border-(--color-sage-light)/20 bg-(--color-cream)/50 p-4 space-y-2 animate-in slide-in-from-bottom-4 motion-reduce:animate-none">
          <ParsedField
            icon={<span>&#128197;</span>}
            label="Deadline"
            value={parsed.deadline ? new Date(parsed.deadline).toLocaleString() : "None"}
            onEdit={() => {/* TODO: deadline picker */}}
          />
          <ParsedField
            icon={<span>&#128193;</span>}
            label="Category"
            value={parsed.category ?? "None"}
            onEdit={() => {/* TODO: category edit */}}
          />
          <ParsedField
            icon={<span>&#9889;</span>}
            label="Energy"
            value={parsed.energy_level ?? "None"}
            onEdit={() => {/* TODO: energy picker */}}
          />
          <ParsedField
            icon={<span>&#9202;</span>}
            label="Estimated"
            value={
              parsed.estimated_minutes
                ? `${parsed.estimated_minutes} min`
                : "None"
            }
            onEdit={() => {/* TODO: time edit */}}
          />
          {parsed.reasoning && (
            <div className="mt-2 flex flex-wrap gap-1.5">
              {Object.entries(parsed.reasoning).map(([key, value]) => (
                <Chip
                  key={key}
                  label={`${key.replace(/detected_/g, "")}: ${value}`}
                  active
                />
              ))}
            </div>
          )}
        </div>
      )}

      {/* Error */}
      {error && (
        <p className="text-sm text-(--color-terracotta)" role="alert">
          {error}
        </p>
      )}

      {/* Action buttons */}
      {(inputState === "parsed" || inputState === "error") && text.trim() && (
        <ActionButtons
          onCancel={onCancel}
          onSave={handleSave}
          saving={inputState === "saving"}
          disabled={!text.trim()}
        />
      )}
    </div>
  );
}

// ── 20. OnboardingStep ────────────────────
// File: src/components/organisms/OnboardingStep.tsx
// 'use client' — interactive: step transitions, form inputs

interface OnboardingStepProps {
  step: 1 | 2 | 3 | 4;
  children: ReactNode;
  isActive: boolean;
}

export function OnboardingStep({ step, children, isActive }: OnboardingStepProps) {
  const headingRef = useRef<HTMLHeadingElement>(null);

  // Focus heading on activation for screen readers
  useEffect(() => {
    if (isActive && headingRef.current) {
      headingRef.current.focus();
    }
  }, [isActive]);

  if (!isActive) return null;

  return (
    <section
      aria-label={`Onboarding step ${step}`}
      className={cn(
        "flex flex-col items-center justify-center min-h-[60vh] px-6",
        "animate-in fade-in slide-in-from-right-4 duration-500",
        "motion-reduce:animate-none"
      )}
    >
      <h2 ref={headingRef} tabIndex={-1} className="sr-only">
        Step {step}
      </h2>
      {children}
    </section>
  );
}

// ── 21. DashboardHeader ───────────────────
// File: src/components/organisms/DashboardHeader.tsx
// Server Component — display only, time-based greeting computed server-side

interface DashboardHeaderProps {
  userName: string | null;
  date: Date;
}

function getGreeting(hour: number): string {
  if (hour < 12) return "Good morning";
  if (hour < 17) return "Good afternoon";
  return "Good evening";
}

export function DashboardHeader({ userName, date }: DashboardHeaderProps) {
  const greeting = getGreeting(date.getHours());
  const formattedDate = date.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  return (
    <header className="space-y-1">
      <h1 className="text-2xl font-bold text-(--color-text)">
        {greeting}
        {userName ? `, ${userName}` : ""}
      </h1>
      <p className="text-sm text-(--color-text)/60">{formattedDate}</p>
    </header>
  );
}

// ════════════════════════════════════════════
// LAYOUTS (2 Templates)
// ════════════════════════════════════════════

// ── 22. DashboardLayout ───────────────────
// File: src/components/layouts/DashboardLayout.tsx
// Server Component — layout wrapper

interface DashboardLayoutProps {
  children: ReactNode;
}

export function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <div className="min-h-dvh bg-(--color-bg)">
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:bg-(--color-sage) focus:text-white focus:rounded-lg"
      >
        Skip to main content
      </a>
      <main
        id="main-content"
        className="mx-auto max-w-[480px] px-4 py-6 sm:max-w-[640px] lg:max-w-[720px]"
      >
        {children}
      </main>
    </div>
  );
}

// ── 23. OnboardingLayout ──────────────────
// File: src/components/layouts/OnboardingLayout.tsx
// 'use client' — interactive: step state management

interface OnboardingLayoutProps {
  children: ReactNode;
  currentStep: number;
  totalSteps: number;
}

export function OnboardingLayout({
  children,
  currentStep,
  totalSteps,
}: OnboardingLayoutProps) {
  return (
    <div className="min-h-dvh bg-(--color-bg) flex flex-col">
      <main className="flex-1 mx-auto max-w-[480px] w-full px-4 sm:max-w-[560px]">
        {children}
      </main>
      <footer className="py-6">
        <ProgressDots totalSteps={totalSteps} currentStep={currentStep} />
      </footer>
    </div>
  );
}
