// Jaanify MVP — Frontend Configuration Files
// Generated by jaan.to frontend-scaffold | 2026-02-09
// Stack: Next.js 15 + React 19 + TailwindCSS v4 + pnpm

// ── package.json ───────────────────────────────────

export const packageJson = {
  name: "jaanify-web",
  version: "0.1.0",
  private: true,
  type: "module",
  engines: { node: ">=22.0.0" },
  scripts: {
    dev: "next dev --turbopack",
    build: "next build",
    start: "next start",
    lint: "eslint .",
    "lint:fix": "eslint . --fix",
    test: "vitest run",
    "test:watch": "vitest",
    "test:e2e": "playwright test",
    "test:e2e:ui": "playwright test --ui",
    storybook: "storybook dev -p 6006",
    "build-storybook": "storybook build",
    "generate:api": "orval --config ./orval.config.ts",
    typecheck: "tsc --noEmit",
  },
  dependencies: {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
    next: "^15.0.0",
    "@tanstack/react-query": "^5.60.0",
    zustand: "^5.0.0",
    nuqs: "^2.5.0",
    "next-themes": "^0.4.0",
    clsx: "^2.1.0",
    "tailwind-merge": "^2.6.0",
    zod: "^3.24.0",
    axios: "^1.7.0",
  },
  devDependencies: {
    typescript: "^5.7.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@types/node": "^22.0.0",
    tailwindcss: "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0",
    eslint: "^9.0.0",
    "eslint-config-next": "^15.0.0",
    "eslint-plugin-jsx-a11y": "^6.10.0",
    prettier: "^3.4.0",
    orval: "^7.0.0",
    vitest: "^2.0.0",
    "@testing-library/react": "^16.0.0",
    "@testing-library/jest-dom": "^6.6.0",
    jsdom: "^25.0.0",
    "@playwright/test": "^1.50.0",
    "@tanstack/react-query-devtools": "^5.60.0",
  },
};

// ── next.config.ts ─────────────────────────────────

export const nextConfigCode = `
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  experimental: {
    reactCompiler: true,
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "lh3.googleusercontent.com" },
    ],
  },
};

export default nextConfig;
`;

// ── postcss.config.mjs ────────────────────────────

export const postcssConfigCode = `
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`;

// ── src/app/globals.css — TailwindCSS v4 CSS-first config ──

export const globalsCss = `
@import "tailwindcss";

/* ── Jaanify Design Tokens ─────────────────────────
   Extracted from design previews (dashboard, task input, onboarding)
   Colors: sage, cream, terracotta, gold palette
   Typography: DM Sans (loaded via next/font)
   ────────────────────────────────────────────────── */

@theme {
  /* Colors — Light mode */
  --color-sage: oklch(0.55 0.08 150);
  --color-sage-dark: oklch(0.45 0.08 150);
  --color-sage-light: oklch(0.75 0.06 150);
  --color-cream: oklch(0.97 0.01 80);
  --color-cream-dark: oklch(0.93 0.02 80);
  --color-terracotta: oklch(0.62 0.12 40);
  --color-terracotta-dark: oklch(0.52 0.12 40);
  --color-gold: oklch(0.72 0.12 85);
  --color-gold-dark: oklch(0.58 0.12 85);
  --color-text: oklch(0.20 0.02 260);
  --color-bg: oklch(0.97 0.005 80);

  /* Typography */
  --font-sans: var(--font-dm-sans), "DM Sans", system-ui, sans-serif;

  /* Spacing scale */
  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 1.5rem;
  --spacing-xl: 2rem;
  --spacing-2xl: 3rem;

  /* Radii */
  --radius-sm: 0.375rem;
  --radius-md: 0.5rem;
  --radius-lg: 0.75rem;
  --radius-xl: 1rem;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-sm: 0 1px 2px oklch(0 0 0 / 0.05);
  --shadow-md: 0 4px 6px oklch(0 0 0 / 0.07);
  --shadow-lg: 0 10px 15px oklch(0 0 0 / 0.1);
}

/* Dark mode tokens */
@custom-variant dark (&:where(.dark, .dark *));

@theme dark {
  --color-sage: oklch(0.65 0.08 150);
  --color-sage-dark: oklch(0.55 0.08 150);
  --color-sage-light: oklch(0.40 0.06 150);
  --color-cream: oklch(0.18 0.01 260);
  --color-cream-dark: oklch(0.15 0.01 260);
  --color-terracotta: oklch(0.70 0.12 40);
  --color-terracotta-dark: oklch(0.60 0.12 40);
  --color-gold: oklch(0.78 0.12 85);
  --color-gold-dark: oklch(0.65 0.12 85);
  --color-text: oklch(0.92 0.01 80);
  --color-bg: oklch(0.14 0.01 260);
}

/* ── Reduced motion ────────────────────────────── */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}

/* ── Scrollbar ─────────────────────────────────── */
@utility scrollbar-none {
  scrollbar-width: none;
  &::-webkit-scrollbar {
    display: none;
  }
}

/* ── Animation utilities ───────────────────────── */
@utility animate-in {
  animation-name: enter;
  animation-duration: 300ms;
  animation-timing-function: cubic-bezier(0.16, 1, 0.3, 1);
  animation-fill-mode: forwards;
}

@utility slide-in-from-bottom-2 {
  --tw-enter-translate-y: 0.5rem;
}

@utility slide-in-from-bottom-4 {
  --tw-enter-translate-y: 1rem;
}

@utility slide-in-from-right-4 {
  --tw-enter-translate-x: 1rem;
}

@utility fade-in {
  --tw-enter-opacity: 0;
}

@keyframes enter {
  from {
    opacity: var(--tw-enter-opacity, 1);
    transform: translate(
      var(--tw-enter-translate-x, 0),
      var(--tw-enter-translate-y, 0)
    );
  }
}
`;

// ── src/lib/cn.ts — clsx + tailwind-merge ─────────

export const cnUtilCode = `
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;

// ── src/lib/api-client.ts — Axios Instance ────────

export const apiClientCode = `
import axios from "axios";

export const apiClient = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000/v1",
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
});

// Request interceptor: attach JWT
apiClient.interceptors.request.use((config) => {
  if (typeof window !== "undefined") {
    const token = localStorage.getItem("jaanify_access_token");
    if (token) {
      config.headers.Authorization = \`Bearer \${token}\`;
    }
  }
  return config;
});

// Response interceptor: handle 401 → refresh token
apiClient.interceptors.response.use(
  (response) => response,
  async (error) => {
    const originalRequest = error.config;
    if (
      error.response?.status === 401 &&
      !originalRequest._retry &&
      !originalRequest.url?.includes("/auth/")
    ) {
      originalRequest._retry = true;
      try {
        const { data } = await apiClient.post<{ access_token: string }>(
          "/auth/refresh"
        );
        localStorage.setItem("jaanify_access_token", data.access_token);
        originalRequest.headers.Authorization = \`Bearer \${data.access_token}\`;
        return apiClient(originalRequest);
      } catch {
        localStorage.removeItem("jaanify_access_token");
        window.location.href = "/onboarding";
      }
    }
    return Promise.reject(error);
  }
);
`;

// ── src/lib/query-client.ts — TanStack Query Config ──

export const queryClientCode = `
import { QueryClient } from "@tanstack/react-query";

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5,       // 5 minutes
      gcTime: 1000 * 60 * 30,          // 30 minutes
      retry: 1,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 0,
    },
  },
});
`;

// ── src/stores/task-store.ts — Zustand Task UI State ──

export const taskStoreCode = `
import { create } from "zustand";
import { persist } from "zustand/middleware";

interface TaskUIState {
  expandedReasoningIds: Set<string>;
  toggleReasoning: (id: string) => void;
  preferredTier: 1 | 2 | 3;
  setPreferredTier: (tier: 1 | 2 | 3) => void;
}

export const useTaskStore = create<TaskUIState>()(
  persist(
    (set) => ({
      expandedReasoningIds: new Set(),
      toggleReasoning: (id) =>
        set((state) => {
          const next = new Set(state.expandedReasoningIds);
          if (next.has(id)) next.delete(id);
          else next.add(id);
          return { expandedReasoningIds: next };
        }),
      preferredTier: 1,
      setPreferredTier: (tier) => set({ preferredTier: tier }),
    }),
    {
      name: "jaanify-task-ui",
      partialize: (state) => ({ preferredTier: state.preferredTier }),
    }
  )
);
`;

// ── src/stores/user-store.ts — Zustand User Preferences ──

export const userStoreCode = `
import { create } from "zustand";
import { persist } from "zustand/middleware";

interface UserPreferences {
  theme: "light" | "dark" | "system";
  setTheme: (theme: "light" | "dark" | "system") => void;
  hasCompletedOnboarding: boolean;
  setOnboardingComplete: () => void;
}

export const useUserStore = create<UserPreferences>()(
  persist(
    (set) => ({
      theme: "system",
      setTheme: (theme) => set({ theme }),
      hasCompletedOnboarding: false,
      setOnboardingComplete: () => set({ hasCompletedOnboarding: true }),
    }),
    { name: "jaanify-user-prefs" }
  )
);
`;

// ── src/stores/onboarding-store.ts — Zustand Onboarding State ──

export const onboardingStoreCode = `
import { create } from "zustand";
import type { TaskParseResponse } from "@/types/api";

interface OnboardingState {
  step: 1 | 2 | 3 | 4;
  setStep: (step: 1 | 2 | 3 | 4) => void;
  taskText: string;
  setTaskText: (text: string) => void;
  parsedTask: TaskParseResponse | null;
  setParsedTask: (task: TaskParseResponse | null) => void;
  guestAnonymousId: string | null;
  setGuestAnonymousId: (id: string) => void;
  reset: () => void;
}

export const useOnboardingStore = create<OnboardingState>()((set) => ({
  step: 1,
  setStep: (step) => set({ step }),
  taskText: "",
  setTaskText: (text) => set({ taskText: text }),
  parsedTask: null,
  setParsedTask: (task) => set({ parsedTask: task }),
  guestAnonymousId: null,
  setGuestAnonymousId: (id) => set({ guestAnonymousId: id }),
  reset: () =>
    set({
      step: 1,
      taskText: "",
      parsedTask: null,
      guestAnonymousId: null,
    }),
}));
`;

// ── src/stores/ui-store.ts — Zustand Global UI State ──

export const uiStoreCode = `
import { create } from "zustand";

interface UIState {
  isMobileMenuOpen: boolean;
  toggleMobileMenu: () => void;
  featureFlags: {
    ENABLE_REASONING_CARDS: boolean;
    ENABLE_VOICE_INPUT: boolean;
    ENABLE_GUEST_MODE: boolean;
  };
}

export const useUIStore = create<UIState>()((set) => ({
  isMobileMenuOpen: false,
  toggleMobileMenu: () =>
    set((state) => ({ isMobileMenuOpen: !state.isMobileMenuOpen })),
  featureFlags: {
    ENABLE_REASONING_CARDS: process.env.NEXT_PUBLIC_ENABLE_REASONING_CARDS !== "false",
    ENABLE_VOICE_INPUT: process.env.NEXT_PUBLIC_ENABLE_VOICE_INPUT !== "false",
    ENABLE_GUEST_MODE: process.env.NEXT_PUBLIC_ENABLE_GUEST_MODE !== "false",
  },
}));
`;

// ── orval.config.ts — API Client Generation ───────

export const orvalConfigCode = `
import { defineConfig } from "orval";

export default defineConfig({
  jaanify: {
    input: {
      target: "../jaan-to/outputs/dev/contract/01-jaanify-mvp/api.yaml",
    },
    output: {
      target: "./src/lib/api/generated/jaanify.ts",
      client: "react-query",
      mode: "single",
      override: {
        mutator: {
          path: "./src/lib/api-client.ts",
          name: "apiClient",
        },
        query: {
          useQuery: true,
          useMutation: true,
        },
      },
    },
  },
});
`;

// ── .env.local.example ────────────────────────────

export const envExample = `# Jaanify Web — Environment Variables
# Copy to .env.local and fill in values

# API
NEXT_PUBLIC_API_URL="http://localhost:3000/v1"

# Auth — Google OAuth2
NEXT_PUBLIC_GOOGLE_CLIENT_ID="YOUR_GOOGLE_CLIENT_ID"

# Feature Flags
NEXT_PUBLIC_ENABLE_REASONING_CARDS="true"
NEXT_PUBLIC_ENABLE_VOICE_INPUT="true"
NEXT_PUBLIC_ENABLE_GUEST_MODE="true"

# Analytics (PostHog)
NEXT_PUBLIC_POSTHOG_KEY=""
NEXT_PUBLIC_POSTHOG_HOST=""
`;

// ── eslint.config.mjs — ESLint 9 Flat Config ─────

export const eslintConfigCode = `
import js from "@eslint/js";
import nextPlugin from "@next/eslint-plugin-next";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import jsxA11y from "eslint-plugin-jsx-a11y";

export default [
  js.configs.recommended,
  {
    files: ["**/*.ts", "**/*.tsx"],
    plugins: {
      "@typescript-eslint": tsPlugin,
      "@next/next": nextPlugin,
      "jsx-a11y": jsxA11y,
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      "@next/next/no-html-link-for-pages": "error",
    },
  },
  {
    ignores: [".next/", "node_modules/", "dist/"],
  },
];
`;
