// Jaanify MVP — Next.js 15 Page Scaffolds
// Generated by jaan.to frontend-scaffold | 2026-02-09
// Stack: Next.js 15 App Router + React 19 Server Components
//
// CONVENTIONS:
// - Pages are Server Components by default
// - Data fetching via async/await in Server Components
// - Client interactivity delegated to organisms/molecules
// - HydrationBoundary for RSC → client data handoff

// ════════════════════════════════════════════
// ROOT LAYOUT
// ════════════════════════════════════════════

// File: src/app/layout.tsx
// Server Component — root layout with providers, font, theme

import type { Metadata, Viewport } from "next";
import { DM_Sans } from "next/font/google";
import { Providers } from "@/providers/Providers";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Jaanify — Smart AI Task Manager",
  description:
    "AI task manager that shows its work. Transparent reasoning, daily plans, and natural language input.",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FAF8F5" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1a1a" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={dmSans.variable} suppressHydrationWarning>
      <body className="font-sans antialiased bg-(--color-bg) text-(--color-text)">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// ════════════════════════════════════════════
// PROVIDERS
// ════════════════════════════════════════════

// File: src/providers/Providers.tsx
// 'use client' — QueryClientProvider, ThemeProvider are client-only

("use client");

import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ThemeProvider } from "next-themes";
import { queryClient } from "@/lib/query-client";

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <QueryClientProvider client={queryClient}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        {children}
      </ThemeProvider>
      {process.env.NODE_ENV === "development" && (
        <ReactQueryDevtools initialIsOpen={false} />
      )}
    </QueryClientProvider>
  );
}

// ════════════════════════════════════════════
// HOME PAGE — Route to dashboard or onboarding
// ════════════════════════════════════════════

// File: src/app/page.tsx
// Server Component — checks auth state and redirects

import { redirect } from "next/navigation";
// TODO: Import auth check from auth library
// import { getSession } from "@/lib/auth";

export default async function HomePage() {
  // TODO: Check auth/guest session state
  // const session = await getSession();
  // if (session) redirect("/dashboard");

  redirect("/onboarding");
}

// ════════════════════════════════════════════
// DASHBOARD PAGE
// ════════════════════════════════════════════

// File: src/app/dashboard/page.tsx
// Server Component with client organism hydration

import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import {
  meQueryOptions,
  taskListQueryOptions,
  planListQueryOptions,
} from "@/hooks/api";
import { DashboardLayout } from "@/components/layouts/DashboardLayout";
import { DashboardContent } from "./DashboardContent";

export default async function DashboardPage() {
  const queryClient = new QueryClient();

  // Prefetch data on server
  await Promise.all([
    queryClient.prefetchQuery(meQueryOptions()),
    queryClient.prefetchQuery(taskListQueryOptions({ status: "active" })),
    queryClient.prefetchQuery(planListQueryOptions({ limit: 1 })),
  ]);

  return (
    <DashboardLayout>
      <HydrationBoundary state={dehydrate(queryClient)}>
        <DashboardContent />
      </HydrationBoundary>
    </DashboardLayout>
  );
}

// File: src/app/dashboard/DashboardContent.tsx
// 'use client' — orchestrates all client-interactive organisms

("use client");

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  useGetMe,
  useListTasks,
  useListDailyPlans,
  useUpdateTask,
  useGenerateDailyPlan,
  useCreateFeedback,
} from "@/hooks/api";
import { DashboardHeader } from "@/components/organisms/DashboardHeader";
import { StatCard } from "@/components/molecules/StatCard";
import { DailyPlanComponent } from "@/components/organisms/DailyPlan";
import { TaskCard } from "@/components/organisms/TaskCard";
import { VoiceFAB } from "@/components/molecules/VoiceFAB";
import { Skeleton } from "@/components/atoms/Skeleton";
import type { TaskResponse, DailyPlanResponse } from "@/types/api";

export function DashboardContent() {
  const router = useRouter();
  const { data: user } = useGetMe();
  const {
    data: taskList,
    isLoading: tasksLoading,
  } = useListTasks({ status: "active" });
  const {
    data: planList,
    isLoading: plansLoading,
  } = useListDailyPlans({ limit: 1 });
  const updateTask = useUpdateTask();
  const generatePlan = useGenerateDailyPlan();
  const createFeedback = useCreateFeedback();

  const [voiceState, setVoiceState] = useState<
    "idle" | "listening" | "processing" | "error" | "unsupported"
  >("idle");

  const todayPlan: DailyPlanResponse | null = planList?.data[0] ?? null;

  const taskMap = new Map<string, TaskResponse>(
    (taskList?.data ?? []).map((t) => [t.id, t])
  );

  const handleComplete = (id: string) => {
    updateTask.mutate({
      id,
      data: { status: "completed" },
    });
  };

  const handleOverride = (taskId: string, reason: string) => {
    createFeedback.mutate({
      task_id: taskId,
      feedback_type: "not_now",
      reason,
    });
  };

  const planState = plansLoading
    ? "loading"
    : !todayPlan && (taskList?.data.length ?? 0) === 0
      ? "empty"
      : todayPlan
        ? "success"
        : "empty";

  // Compute stats from task data
  const completedToday = (taskList?.data ?? []).filter(
    (t) => t.completed_at && new Date(t.completed_at).toDateString() === new Date().toDateString()
  ).length;

  return (
    <div className="space-y-6">
      <DashboardHeader
        userName={user?.name?.split(" ")[0] ?? null}
        date={new Date()}
      />

      {/* Stats row */}
      <div className="grid grid-cols-3 gap-3">
        {tasksLoading ? (
          <>
            <Skeleton className="h-24" variant="rectangular" />
            <Skeleton className="h-24" variant="rectangular" />
            <Skeleton className="h-24" variant="rectangular" />
          </>
        ) : (
          <>
            <StatCard
              icon={<span>&#10003;</span>}
              value={completedToday}
              label="Done today"
            />
            <StatCard
              icon={<span>&#9201;</span>}
              value="—"
              label="Focus time"
            />
            <StatCard
              icon={<span>&#128293;</span>}
              value="—"
              label="Streak"
            />
          </>
        )}
      </div>

      {/* Daily plan */}
      <DailyPlanComponent
        plan={todayPlan}
        tasks={taskMap}
        state={planState as "loading" | "success" | "error" | "empty" | "refreshing"}
        onGenerate={() => generatePlan.mutate()}
        onAddTask={() => router.push("/tasks/new")}
        onRefresh={() => generatePlan.mutate()}
      />

      {/* Task list (non-planned tasks) */}
      {!tasksLoading && (taskList?.data ?? []).length > 0 && (
        <section aria-label="All tasks" className="space-y-3">
          <h2 className="text-sm font-medium text-(--color-text)/60 uppercase tracking-wide">
            All Tasks
          </h2>
          {taskList?.data.map((task) => (
            <TaskCard
              key={task.id}
              task={task}
              onComplete={handleComplete}
              onOverride={handleOverride}
            />
          ))}
        </section>
      )}

      {/* Voice FAB */}
      <VoiceFAB
        state={voiceState}
        onPress={() => {
          // TODO: Implement Web Speech API
          router.push("/tasks/new");
        }}
        onStop={() => setVoiceState("idle")}
      />
    </div>
  );
}

// ════════════════════════════════════════════
// TASK INPUT PAGE
// ════════════════════════════════════════════

// File: src/app/tasks/new/page.tsx
// Server Component wrapper with client form

import { TaskInputContent } from "./TaskInputContent";

export default function TaskInputPage() {
  return <TaskInputContent />;
}

// File: src/app/tasks/new/TaskInputContent.tsx
// 'use client' — full form interactivity

("use client");

import { useRouter } from "next/navigation";
import { useCreateTask, useParseTask } from "@/hooks/api";
import { TaskInputForm } from "@/components/organisms/TaskInputForm";
import type { TaskParseResponse } from "@/types/api";

export function TaskInputContent() {
  const router = useRouter();
  const createTask = useCreateTask();
  const parseTask = useParseTask();

  const handleParse = async (input: string): Promise<TaskParseResponse> => {
    return parseTask.mutateAsync({ input });
  };

  const handleSave = (data: {
    title: string;
    raw_input: string;
    parsed: TaskParseResponse | null;
  }) => {
    createTask.mutate(
      {
        title: data.title,
        raw_input: data.raw_input,
        deadline: data.parsed?.deadline,
        category: data.parsed?.category,
        energy_level: data.parsed?.energy_level,
        estimated_minutes: data.parsed?.estimated_minutes,
      },
      {
        onSuccess: () => router.push("/dashboard"),
      }
    );
  };

  return (
    <div className="min-h-dvh bg-(--color-bg) flex flex-col justify-center py-8">
      <div className="mb-4 px-4">
        <button
          onClick={() => router.back()}
          className="text-(--color-text)/60 hover:text-(--color-text) text-sm flex items-center gap-1"
          aria-label="Go back"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </button>
      </div>
      <TaskInputForm
        onSave={handleSave}
        onCancel={() => router.back()}
        onParse={handleParse}
      />
    </div>
  );
}

// ════════════════════════════════════════════
// ONBOARDING PAGE
// ════════════════════════════════════════════

// File: src/app/onboarding/page.tsx
// Server Component wrapper

import { OnboardingContent } from "./OnboardingContent";

export default function OnboardingPage() {
  return <OnboardingContent />;
}

// File: src/app/onboarding/OnboardingContent.tsx
// 'use client' — 4-step flow with Zustand state

("use client");

import { useRouter } from "next/navigation";
import { OnboardingLayout } from "@/components/layouts/OnboardingLayout";
import { OnboardingStep } from "@/components/organisms/OnboardingStep";
import { Button } from "@/components/atoms/Button";
import { ReasoningCard } from "@/components/organisms/ReasoningCard";
import { PlanTaskRow } from "@/components/molecules/PlanTaskRow";
import { useOnboardingStore } from "@/stores/onboarding-store";
import { useCreateGuestSession, useParseTask, useAuthGoogle } from "@/hooks/api";
import type { TaskParseResponse, ReasoningJson } from "@/types/api";

export function OnboardingContent() {
  const router = useRouter();
  const { step, setStep, taskText, setTaskText, parsedTask, setParsedTask } =
    useOnboardingStore();
  const createGuest = useCreateGuestSession();
  const parseTask = useParseTask();

  const handleStep1Submit = async () => {
    if (taskText.length < 4) return;

    // Create guest session
    createGuest.mutate({ data_json: { first_task: taskText } });

    // Parse the task
    try {
      const result = await parseTask.mutateAsync({ input: taskText });
      setParsedTask(result);
      setStep(2);
    } catch {
      // Still advance — show with mock data
      setStep(2);
    }
  };

  const handleComplete = (skippedAccount: boolean) => {
    if (skippedAccount) {
      router.push("/dashboard");
    }
    // TODO: Handle Google OAuth completion
  };

  // Demo reasoning for Step 2
  const demoReasoning: ReasoningJson = parsedTask
    ? {
        tier1: `Prioritized because: ${parsedTask.category ?? "personal task"} with ${
          parsedTask.deadline ? "upcoming deadline" : "no deadline"
        }`,
        factors: {
          deadline: parsedTask.deadline ? 0.35 : 0.1,
          importance: 0.25,
          energy: 0.2,
          context: 0.2,
        },
        confidence: parsedTask.confidence ?? 0.85,
      }
    : {
        tier1: "High priority — deadline approaching",
        factors: { deadline: 0.35, importance: 0.25, energy: 0.2, context: 0.2 },
        confidence: 0.85,
      };

  return (
    <OnboardingLayout currentStep={step - 1} totalSteps={4}>
      {/* Step 1: "What's on your mind?" */}
      <OnboardingStep step={1} isActive={step === 1}>
        <div className="text-center space-y-6 w-full max-w-sm">
          <h1 className="text-3xl font-bold text-(--color-text)">
            What&apos;s on your mind?
          </h1>
          <p className="text-(--color-text)/60">
            Type one task. We&apos;ll show you something cool.
          </p>
          <textarea
            value={taskText}
            onChange={(e) => setTaskText(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleStep1Submit();
              }
            }}
            placeholder="e.g. Call Sarah about the proposal by Friday"
            className="w-full bg-transparent border-0 border-b-2 border-(--color-sage-light)/30 text-xl text-(--color-text) placeholder:text-(--color-text)/30 focus:border-(--color-sage) focus:outline-none resize-none py-3 text-center"
            rows={2}
            autoFocus
            aria-label="Enter your first task"
          />
          {taskText.length >= 4 && (
            <div className="animate-in slide-in-from-bottom-2 motion-reduce:animate-none">
              <Button onClick={handleStep1Submit} loading={parseTask.isPending}>
                Show me the magic
              </Button>
            </div>
          )}
        </div>
      </OnboardingStep>

      {/* Step 2: AI Enrichment "aha" moment */}
      <OnboardingStep step={2} isActive={step === 2}>
        <div className="space-y-6 w-full max-w-sm">
          <div className="text-center">
            <h2 className="text-xl font-bold text-(--color-text) mb-2">
              Here&apos;s what we found
            </h2>
            <p className="text-sm text-(--color-text)/60">
              AI analyzed your task and here&apos;s the reasoning
            </p>
          </div>

          {/* Enriched task card */}
          <div className="rounded-xl border border-(--color-sage-light)/20 bg-(--color-cream)/50 p-4 space-y-3">
            <h3 className="font-medium text-(--color-text)">
              {parsedTask?.title ?? taskText}
            </h3>
            {parsedTask?.deadline && (
              <p className="text-sm text-(--color-text)/60">
                Deadline: {new Date(parsedTask.deadline).toLocaleDateString()}
              </p>
            )}
            {parsedTask?.category && (
              <p className="text-sm text-(--color-text)/60">
                Category: {parsedTask.category}
              </p>
            )}
          </div>

          {/* The "aha" moment — Reasoning Card */}
          <ReasoningCard reasoning={demoReasoning} />

          <Button onClick={() => setStep(3)} className="w-full">
            See your day planned
          </Button>
        </div>
      </OnboardingStep>

      {/* Step 3: Daily Plan Preview */}
      <OnboardingStep step={3} isActive={step === 3}>
        <div className="space-y-6 w-full max-w-sm">
          <div className="text-center">
            <h2 className="text-xl font-bold text-(--color-text) mb-2">
              Your day, planned
            </h2>
            <p className="text-sm text-(--color-text)/60">
              AI orders your tasks based on deadlines, energy, and priority
            </p>
          </div>

          {/* Demo plan with the user's task + 2 sample tasks */}
          <div className="rounded-xl border border-(--color-sage-light)/20 bg-(--color-cream)/50 p-4 space-y-1">
            {/* User's task at #1 */}
            <div className="flex items-start gap-3 py-3 border-b border-(--color-sage-light)/10">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-(--color-sage)/15 text-(--color-sage) text-xs font-bold flex items-center justify-center">
                1
              </span>
              <div>
                <p className="font-medium text-(--color-text)">{parsedTask?.title ?? taskText}</p>
                <p className="text-xs text-(--color-sage)">
                  {demoReasoning.tier1}
                </p>
              </div>
            </div>
            {/* Sample tasks */}
            <div className="flex items-start gap-3 py-3 border-b border-(--color-sage-light)/10">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-(--color-sage)/15 text-(--color-sage) text-xs font-bold flex items-center justify-center">
                2
              </span>
              <div>
                <p className="font-medium text-(--color-text)/60">Review weekly report</p>
                <p className="text-xs text-(--color-text)/40">Medium priority — end of day</p>
              </div>
            </div>
            <div className="flex items-start gap-3 py-3">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-(--color-sage)/15 text-(--color-sage) text-xs font-bold flex items-center justify-center">
                3
              </span>
              <div>
                <p className="font-medium text-(--color-text)/60">Organize desk</p>
                <p className="text-xs text-(--color-text)/40">Low energy — whenever</p>
              </div>
            </div>
          </div>

          <Button onClick={() => setStep(4)} className="w-full">
            Almost done
          </Button>
        </div>
      </OnboardingStep>

      {/* Step 4: Soft Account Prompt */}
      <OnboardingStep step={4} isActive={step === 4}>
        <div className="space-y-6 w-full max-w-sm text-center">
          <h2 className="text-xl font-bold text-(--color-text)">
            Save your progress?
          </h2>
          <p className="text-sm text-(--color-text)/60">
            Your tasks are saved for 7 days. Sign in to keep them forever.
          </p>

          {/* Google OAuth button */}
          <Button
            variant="primary"
            className="w-full"
            onClick={() => {
              // TODO: Trigger Google OAuth flow
              handleComplete(false);
            }}
          >
            <svg className="h-5 w-5 mr-2" viewBox="0 0 24 24">
              <path
                d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 01-2.2 3.32v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.1z"
                fill="#4285F4"
              />
              <path
                d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                fill="#34A853"
              />
              <path
                d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                fill="#FBBC05"
              />
              <path
                d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                fill="#EA4335"
              />
            </svg>
            Continue with Google
          </Button>

          {/* Skip button — visible, not hidden */}
          <button
            onClick={() => handleComplete(true)}
            className="text-(--color-text)/50 hover:text-(--color-text) text-sm underline underline-offset-4"
          >
            Skip for now — I&apos;ll sign in later
          </button>

          <p className="text-xs text-(--color-text)/40">
            We only use your email to sync tasks across devices.
            No spam, ever.
          </p>
        </div>
      </OnboardingStep>
    </OnboardingLayout>
  );
}
